'use strict';
/* Samoth Companion V3. One canonical state, one transaction per committed action. */
const KEY='samoth-companion-v3',MAX={1:4,2:3,3:3,4:3,5:2},SP_COST={1:2,2:3,3:5,4:6,5:7};
const SPELLS=[
{id:'rayon',name:'Rayon de givre',lv:0,kind:'attack',dice:[2,8],cold:true,range:'18 m',components:'V, S',desc:'Attaque +10. Touché : froid, vitesse de la cible réduite de 3 m jusqu’au début du prochain tour.',twin:true},
{id:'water',name:'Façonnage de l’eau',lv:0,range:'9 m',components:'S',duration:'Instantané ou 1 h',desc:'Déplacer, colorer, façonner ou geler un cube de 1,5 m d’eau ; deux effets non instantanés.'},
{id:'frostbite',name:'Gelure',lv:0,kind:'save',save:'CON',dice:[2,6],cold:true,twin:true,range:'18 m',components:'V, S',desc:'Échec au JDS : froid et désavantage à la prochaine attaque avec arme avant la fin du prochain tour.'},
{id:'illusion',name:'Illusion mineure',lv:0,range:'9 m',components:'S, M',duration:'1 min',desc:'Son ou image dans un cube de 1,5 m ; interaction physique révèle l’illusion.'},
{id:'magehand',name:'Main de mage',lv:0,range:'9 m',components:'V, S',duration:'1 min',desc:'Manipuler à distance un objet de 5 kg maximum, sans attaque ni objet magique.'},
{id:'prestidigitation',name:'Prestidigitation',lv:0,range:'3 m',components:'V, S',duration:'Jusqu’à 1 h',desc:'Effets magiques mineurs ; jusqu’à trois effets persistants simultanément.'},
{id:'absorb',name:'Absorption des éléments',lv:1,kind:'reaction',range:'Personnelle',components:'S',duration:'1 round',desc:'Résistance temporaire à acide, froid, feu, foudre ou tonnerre ; +1d6 du type absorbé sur le premier toucher au corps à corps suivant.'},
{id:'missile',name:'Projectile magique',lv:1,kind:'automatic',range:'36 m',components:'V, S',desc:'Trois projectiles automatiques de 1d4+1 force, +1 projectile par niveau supérieur.'},
{id:'shield',name:'Bouclier',lv:1,kind:'reaction',range:'Personnelle',components:'V, S',duration:'1 round',desc:'+5 CA jusqu’au début de votre prochain tour ; annule Projectile magique contre vous.'},
{id:'orb',name:'Orbe chromatique',lv:1,kind:'attack',dice:[3,8],range:'27 m',components:'V, S, M',twin:true,desc:'Attaque +10 ; 3d8 du type choisi, +1d8 par niveau supérieur. Choisir froid pour la spécialisation.'},
{id:'cure',name:'Soins',lv:1,kind:'heal',range:'Contact',components:'V, S',desc:'1d8+3 PV, +1d8 par niveau supérieur ; une utilisation gratuite par repos long grâce au Présent du dragon métallique.'},
{id:'haste',name:'Hâte',lv:3,concentration:true,twin:true,range:'9 m',components:'V, S, M',duration:'10 rounds',desc:'+2 CA, avantage JDS DEX, vitesse doublée et action supplémentaire limitée. Léthargie un tour à la fin.'},
{id:'counter',name:'Contresort',lv:3,kind:'reaction',range:'18 m',components:'S',desc:'Interruption automatique si niveau du sort cible ≤ niveau de l’emplacement ; sinon test de Charisme +7, DD 10 + niveau ciblé.'},
{id:'vortex',name:'Vortex de glace',lv:3,kind:'save',save:'DEX',dice:[8,6],cold:true,half:true,range:'45 m',components:'V, S, M',desc:'Sphère rayon 6 m ; 8d6 froid, moitié en réussite, +1d6 par niveau supérieur. Adaptation maison de Boule de feu.'},
{id:'invisibility',name:'Invisibilité supérieure',lv:4,concentration:true,twin:true,range:'Contact',components:'V, S',duration:'10 rounds',desc:'Invisible même après une attaque ou une incantation.'},
{id:'radiance',name:'Rayonnement écœurant',lv:4,concentration:true,range:'36 m',components:'V, S',duration:'10 min',desc:'Sphère rayon 9 m ; CON DD18, 4d10 radiant et un épuisement en échec à chaque exposition.'},
{id:'storm',name:'Tempête de grêle',lv:4,kind:'storm',save:'DEX',half:true,range:'90 m',components:'V, S, M',desc:'Cylindre rayon 6 m ; 2d8 contondant +4d6 froid, moitié en réussite. Terrain difficile un tour.'},
{id:'cone',name:'Cône de froid',lv:5,kind:'save',save:'CON',dice:[8,8],cold:true,half:true,range:'Cône 18 m',components:'V, S, M',desc:'8d8 froid, moitié en réussite ; +1d8 par niveau supérieur.'},
{id:'dragon',name:'Convocation d’esprit draconique',lv:5,kind:'summon',concentration:true,range:'18 m',components:'V, S, M (objet gravé ≥500 po)',duration:'1 h',desc:'Esprit métallique d’argent, CA19, PV50. Deux Déchirements et Souffle ; agit après Samoth.'}
];
const initialItems=[
['Bâton de confluence','equipment',1,'8 charges. Mains 1, Vortex 3 ; 1d4+2 charges à l’aube.'],['Dague','equipment',2,'+4, 1d4+1 perforant.'],['Fiole sanguine','equipment',1,'Liée : +2 à l’attaque de sort et au DD déjà intégrés ; +5 SP une fois/jour si dé de vie dépensé.'],['Anneau de chaleur constante','equipment',1,'Effet à confirmer à la table.'],['Anneau de transplanation chaotique','equipment',1,'Effet à confirmer à la table.'],['Anneau en bois','equipment',1,'Régénération 1d6 PV par heure selon validation du MJ.'],['Potion de soin mineur','misc',6,'Consommable ; montant des soins selon le MJ.'],['Potion de soin majeur','misc',2,'Consommable ; montant des soins selon le MJ.'],['Potion d’immunité au froid','misc',1,'Consommable.'],['Potion de résistance tonnerre','misc',1,'Consommable.'],['Antivenin','misc',1,'Consommable.']].map(([name,category,qty,note])=>({id:crypto.randomUUID(),name,category,qty,note,image:'',equipped:category==='equipment'}));
function fresh(){return{schema:3,hp:72,tempHp:0,round:1,phase:'samoth',eco:{action:false,bonus:false,reaction:false,move:false},dragonEco:{action:false,move:false,rends:0,breath:false},turnDamage:0,dragonDamage:0,slots:{...MAX},sp:10,featSp:0,featEnabled:false,intensified:false,concentration:'',dragon:null,sharedResistance:'',cureFree:1,wings:4,flame:1,flameArmed:false,vial:1,staff:8,hitDice:10,bonusSpell:false,leveledAction:false,meta:'none',history:[],notes:'',npcs:[],items:structuredClone(initialItems),preview:true,undo:null};}
function migrateOld(){let oldRaw=localStorage.getItem('samoth-v3');if(!oldRaw)return fresh();let old=JSON.parse(oldRaw);if(old.schema!==3||!Number.isFinite(old.hp)||!old.slots)throw Error('Ancien combat incompatible');let next=fresh();next.hp=Math.max(0,Math.min(72,old.hp));next.tempHp=Math.max(0,old.tempHp||0);next.slots={...MAX,...old.slots};next.sp=Math.max(0,Math.min(10,old.spCore??10));next.featEnabled=Number.isFinite(old.spBonus)||Number.isFinite(old.spMeta);next.featSp=next.featEnabled?Math.max(0,Math.min(2,old.spBonus??old.spMeta??2)):0;next.concentration=old.concentration||old.conc||'';next.dragon=old.dragon?{hp:old.dragonHp||50,max:50,ac:19,level:5}:null;next.phase=old.phase==='dragon'&&next.dragon?'dragon':'samoth';next.round=old.round||1;next.eco={...next.eco,...old.eco};next.wings=old.wings??4;next.cureFree=old.freeHeal??1;next.flame=old.pure??1;next.flameArmed=!!old.pureArmed;next.vial=old.vial??1;next.staff=old.staff??8;next.turnDamage=old.turnDamage||0;next.history=(old.journal||[]).slice(0,150).map(e=>({at:new Date().toISOString(),round:e.round||1,actor:'samoth',title:e.title||'Ancien événement',detail:e.detail||'',kind:e.type||'action'}));let surfacesRaw=localStorage.getItem('companion-v3:samoth:'+location.pathname.replace(/index\.html$/,''));if(surfacesRaw){let x=JSON.parse(surfacesRaw);if(x.schema===1){next.items=(x.items||[]).map(i=>({...i,id:crypto.randomUUID(),category:i.category==='equipment'?'equipment':'misc',equipped:!!i.active}));next.notes=x.notes||'';next.npcs=x.npcs||[];next.preview=x.preview??true}}return next}
let state;let loadError='';try{let raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):migrateOld();if(state.schema!==3||!Array.isArray(state.history)||!Array.isArray(state.items)||!state.slots||!state.eco)throw Error('Sauvegarde incompatible');}catch(e){state=fresh();loadError='Ancienne sauvegarde illisible conservée : exportez-la depuis le stockage du navigateur avant remise à zéro.';}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>structuredClone(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){message('Stockage saturé : exportez votre partie (images locales volumineuses).');return false}}
function roll(sides){return Math.floor(Math.random()*sides)+1}
function dice(n,s,cold=false){let raw=Array.from({length:n},()=>roll(s));return{raw,values:raw.map(v=>cold&&v===1?2:v),get total(){return this.values.reduce((a,b)=>a+b,0)}}}
function damageDice(n,s,cold=false,empowered=false){let d=dice(n,s,cold),before=[...d.values];if(empowered){let indexes=d.values.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]).slice(0,3);for(let[,i]of indexes){d.raw[i]=roll(s);d.values[i]=cold&&d.raw[i]===1?2:d.raw[i]}}return{total:d.total,detail:d.values.join('+')+(empowered?' [relance '+before.join('+')+']':'')}}
function message(msg){$('#resultText').textContent=msg;$('#result').hidden=false}
function effect(kind){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let node=$('#fx');node.classList.remove('play');void node.offsetWidth;node.classList.add('play');setTimeout(()=>node.classList.remove('play'),900)}
function commit(before,title,detail,kind='action'){let snapshot=clone(before);snapshot.undo=null;state.undo=snapshot;state.history.unshift({at:new Date().toISOString(),round:state.round,actor:state.phase,title,detail,kind});state.history=state.history.slice(0,150);persist();render();message(`${title}\n${detail}`);if(['crit','summon','flame'].includes(kind))effect(kind)}
function transaction(title,fn){const before=clone(state),result=fn();if(result===false)return false;commit(before,title,typeof result==='string'?result:'');return true}
function requireCost(cost){if(state.phase==='dragon'&&cost!=='reaction'){message('Terminez d’abord le tour du dragon.');return false}if(state.eco[cost]){message(`${cost==='bonus'?'Action bonus':cost==='reaction'?'Réaction':'Action'} déjà utilisée.`);return false}return true}
function spendPoints(cost){let feat=Math.min(cost,state.featSp);if(state.sp<cost-feat)return false;state.featSp-=feat;state.sp-=cost-feat;return true}
function canPoints(cost){return state.sp+state.featSp>=cost}
function getSpell(id){return SPELLS.find(s=>s.id===id)}
function choose(title,body,buttons){return new Promise(resolve=>{let dlg=$('#resolution');$('#resolutionTitle').textContent=title;$('#resolutionBody').innerHTML=body;$('#resolutionActions').innerHTML='';$('#resolutionActions').className='dialog-actions';for(let b of buttons){let btn=document.createElement('button');btn.type='button';btn.textContent=b.label;btn.className=b.value===null?'cancel':'';btn.onclick=()=>{let data={};$$('#resolutionBody input,#resolutionBody select').forEach(e=>data[e.name]=e.value);dlg.close();resolve({choice:b.value,data})};$('#resolutionActions').append(btn)}dlg.oncancel=e=>{e.preventDefault();dlg.close();resolve({choice:null,data:{}})};dlg.showModal()})}
async function askNumber(label,def=1,min=0,max=999){let x=await choose(label,`<label>${esc(label)} <input name="amount" type="number" min="${min}" max="${max}" value="${def}"></label>`,[{label:'Valider',value:'ok'},{label:'Annuler',value:null}]);if(x.choice===null)return null;let n=Number(x.data.amount);if(!Number.isFinite(n)||n<min||n>max){message('Valeur invalide.');return null}return Math.floor(n)}
async function askText(title,fields,existing={}){let body=fields.map(f=>`<label>${esc(f.label)} ${f.type==='textarea'?`<textarea name="${f.key}" rows="4">${esc(existing[f.key]||'')}</textarea>`:`<input name="${f.key}" type="${f.type||'text'}" value="${esc(existing[f.key]??'')}" maxlength="${f.max||5000}">`}</label>`).join('');let r=await choose(title,body,[{label:'Enregistrer',value:'save'},{label:'Annuler',value:null}]);return r.choice?r.data:null}
function attackRoll(){let manual=Number($('#manual').value),mode=$('[data-rollmode].on')?.dataset.rollmode||'normal';if($('#manual').value!==''&&Number.isInteger(manual)&&manual>=1&&manual<=20)return{nat:manual,display:`d20 manuel ${manual}`};let a=roll(20),b=mode==='normal'?null:roll(20);return{nat:b===null?a:mode==='adv'?Math.max(a,b):Math.min(a,b),display:b===null?`d20 ${a}`:`d20 ${a} / ${b} (${mode==='adv'?'avantage':'désavantage'})`}}
function usableSpell(s,level,meta,free){let cost=s.kind==='reaction'?'reaction':meta==='quick'?'bonus':'action';if(!requireCost(cost))return false;if(s.kind==='reaction'&&meta!=='none'){message('Métamagie indisponible sur cette réaction.');return false}if(meta==='quick'&&s.kind==='reaction'){message('Une réaction ne peut pas être accélérée.');return false}if(cost==='action'&&state.bonusSpell&&s.lv>0){message('Après un sort en action bonus, seul un tour de magie à 1 action est autorisé.');return false}if(cost==='bonus'&&state.leveledAction){message('Un sort de niveau a déjà été lancé avec l’action ce tour.');return false}if(!free&&s.lv&&state.slots[level]<=0){message(`Plus d’emplacements de niveau ${level}.`);return false}let points=meta==='quick'?2:meta==='twin'?(level||1):meta==='heighten'?3:meta==='empower'?1:0;if(meta==='twin'&&!s.twin||meta==='heighten'&&!(s.kind==='save'||s.kind==='storm'||s.id==='radiance')){message('Cette métamagie ne s’applique pas à ce sort.');return false}if(meta==='heighten'&&!state.intensified){message('Sort intensifié non validé dans la configuration.');return false}if(!canPoints(points)){message('Points de sorcellerie insuffisants.');return false}return{cost,points}}
function spellDice(s,level){if(s.id==='orb')return[3+level-1,8];if(s.id==='vortex')return[8+level-3,6];if(s.id==='cone')return[8+level-5,8];return s.dice||[0,0]}
function applyCast(s,level,meta,free,guard){if(!free&&level)state.slots[level]--;if(free)state.cureFree=0;spendPoints(guard.points);state.eco[guard.cost]=true;if(guard.cost==='bonus')state.bonusSpell=true;else if(guard.cost==='action'&&s.lv>0)state.leveledAction=true;state.meta='none';if(s.concentration){if(state.dragon){state.dragon=null;state.sharedResistance=''}state.concentration=s.name}}
async function cast(id){let s=getSpell(id);if(!s)return;let meta=state.meta,free=s.id==='cure'&&state.cureFree>0,level=s.lv;
 if(s.lv&&!(s.id==='cure'&&free)){let opts=Object.keys(MAX).map(Number).filter(n=>n>=s.lv&&state.slots[n]>0);if(!opts.length){message('Plus aucun emplacement compatible.');return}let r=await choose(s.name,`<label>Emplacement <select name="level">${opts.map(n=>`<option value="${n}" ${n===s.lv?'selected':''}>Niveau ${n} · ${state.slots[n]} restant(s)</option>`).join('')}</select></label>`,[{label:'Continuer',value:'go'},...(s.id==='cure'&&state.cureFree?[{label:'Usage gratuit',value:'free'}]:[]),{label:'Annuler',value:null}]);if(!r.choice)return;level=r.choice==='free'?1:Number(r.data.level);free=r.choice==='free'}
 else if(s.id==='cure'&&free){let r=await choose('Soins',`<p>Une utilisation gratuite du don est disponible.</p><label>Ou emplacement <select name="level">${Object.keys(MAX).filter(n=>state.slots[n]>0).map(n=>`<option value="${n}">Niveau ${n}</option>`).join('')}</select></label>`,[{label:'Usage gratuit',value:'free'},...(Object.values(state.slots).some(Boolean)?[{label:'Utiliser emplacement',value:'slot'}]:[]),{label:'Annuler',value:null}]);if(!r.choice)return;free=r.choice==='free';level=free?1:Number(r.data.level)}
 let guard=usableSpell(s,level,meta,free);if(!guard)return;
 let detail='',pendingDamage=0,critical=false,attackResults=[];
 if(s.kind==='attack'){
   let hits=meta==='twin'?2:1;
   for(let i=0;i<hits;i++){let ar=attackRoll(),nat=ar.nat,auto=nat===1?'raté automatique':nat===20?'critique automatique':'';let r=await choose(`${s.name} · cible ${i+1}`,`<p><b>${esc(ar.display)} +10 = ${nat+10}</b> ${auto}</p><p>La cible est-elle touchée ? Les dégâts seront lancés après confirmation.</p>`,[{label:'Touché',value:'hit'},{label:'Raté',value:'miss'},{label:'Annuler le sort',value:null}]);if(!r.choice)return;let hit=nat===1?false:nat===20?true:r.choice==='hit';attackResults.push({nat,hit});}
 }
 let orbCold=true;if(s.id==='orb'){let r=await choose('Type de dégâts',`<label>Élément <select name="type">${['froid','acide','feu','foudre','poison','tonnerre'].map(x=>`<option>${x}</option>`).join('')}</select></label>`,[{label:'Valider',value:'ok'},{label:'Annuler',value:null}]);if(!r.choice)return;orbCold=r.data.type==='froid';s={...s,cold:orbCold,element:r.data.type}}
 let fail=0,success=0;
 if(['save','storm'].includes(s.kind)){let r=await choose(`${s.name} · JDS ${s.save} DD18`,`<div class="field-row"><label>Échecs <input name="fail" type="number" min="0" value="${meta==='twin'?2:1}"></label><label>Réussites <input name="success" type="number" min="0" value="0"></label></div><p>${meta==='heighten'?'Une première sauvegarde subit le désavantage. ':''}Indiquer les créatures concernées.</p>`,[{label:'Résoudre',value:'ok'},{label:'Annuler',value:null}]);if(!r.choice)return;fail=Number(r.data.fail);success=Number(r.data.success);if(!Number.isInteger(fail)||!Number.isInteger(success)||fail<0||success<0||fail+success>50||(meta==='twin'&&fail+success>2)){message('Nombre de cibles invalide.');return}}
 let summonResistance='';if(s.kind==='summon'){let r=await choose('Résistance partagée',`<label>Choix du dragon métallique <select name="type">${['froid','acide','feu','foudre','poison'].map(t=>`<option>${t}</option>`).join('')}</select></label>`,[{label:'Invoquer',value:'ok'},{label:'Annuler',value:null}]);if(!r.choice)return;summonResistance=r.data.type}
 const before=clone(state);applyCast(s,level,meta,free,guard);if(s.kind==='summon')state.sharedResistance=summonResistance;
 if(s.kind==='attack'){let pieces=[];for(let [i,r]of attackResults.entries()){if(!r.hit){pieces.push(`Cible ${i+1} : ${r.nat}+10=${r.nat+10} · raté${r.nat===1?' (1 naturel)':''}`);continue}let[n,faces]=spellDice(s,level),d=damageDice(n*(r.nat===20?2:1),faces,!!s.cold,meta==='empower'),bonus=s.cold?3:0;let extra=state.flameArmed&&level>0?damageDice(level,10):null;if(extra){state.flameArmed=false;state.flame=0}let amount=d.total+bonus+(extra?.total||0);pendingDamage+=amount;critical ||=r.nat===20;pieces.push(`Cible ${i+1} : ${r.nat}+10=${r.nat+10}${r.nat===20?' · CRITIQUE':''}\n${amount} dégâts (${d.total}${s.cold?' froid':s.element?' '+s.element:''}${bonus?' + 3 affinité':''}${extra?' + '+extra.total+' radiant':''}) · dés ${d.detail}`)}detail=pieces.join('\n');}
 else if(s.kind==='save'||s.kind==='storm'){let d,parts;if(s.kind==='storm'){let a=damageDice(2+level-4,8,false,false),b=damageDice(4,6,true,false);d={total:a.total+b.total+3,detail:`${a.detail} contondant + ${b.detail} froid +3 affinité`};parts=`${a.total} contondant + ${b.total+3} froid`}else{let[n,faces]=spellDice(s,level);d=damageDice(n,faces,!!s.cold,meta==='empower');d.total+=s.cold?3:0;parts=`${d.total} ${s.cold?'froid':'dégâts'}`}let extra=state.flameArmed&&level>0&&fail+success>0?damageDice(level,10):null;if(extra){state.flameArmed=false;state.flame=0}let full=d.total+(extra?.total||0),half=s.half?Math.floor(full/2):0;pendingDamage=fail*full+success*half;detail=`${s.save} DD18 · ${fail} échec(s), ${success} réussite(s)\n${pendingDamage} dégâts cumulés (${parts}${extra?' + '+extra.total+' radiant':''}) · ${full} par échec, ${half} par réussite. Dés : ${d.detail}${meta==='heighten'?' · premier JDS avec désavantage':''}`}
 else if(s.kind==='automatic'){let count=3+level-1;let d=damageDice(count,4);pendingDamage=d.total+count;detail=`${count} projectiles · ${pendingDamage} force (${d.detail} + ${count}) · répartition libre, toucher automatique.`}
 else if(s.kind==='heal'){let d=damageDice(level,8);detail=`${d.total+3} PV rendus (dés ${d.detail} +3). ${free?'Usage gratuit consommé.':'Emplacement niveau '+level+'.'}`}
 else if(s.kind==='summon'){state.dragon={hp:50,max:50,ac:19,level:5};state.dragonEco={action:false,move:false,rends:0,breath:false};detail=`Dragon d’argent invoqué · 50 PV · CA19 · résistance partagée : ${state.sharedResistance} · joue après Samoth.`}
 else if(s.id==='counter'){let d=roll(20);detail=`Emplacement ${level} : interruption automatique des sorts de niveau ≤${level}. Si niveau supérieur : test de Charisme d20 ${d}+7=${d+7} contre DD 10 + niveau du sort adverse.`}
 else if(s.id==='shield')detail='+5 CA jusqu’au début du prochain tour ; immunité au Projectile magique.';
 else if(s.id==='absorb')detail='Résistance au type déclencheur jusqu’au début du prochain tour ; bonus à la prochaine attaque de mêlée.';
 else if(s.id==='radiance')detail='Zone maintenue. Pour chaque exposition : CON DD18, échec 4d10 radiant et 1 épuisement. Concentrez-vous.';
 else detail=`${s.desc}${s.concentration?' · Concentration active.':''}`;
 state.turnDamage+=pendingDamage;commit(before,s.name,detail+(meta!=='none'?`\nMétamagie : ${meta} (${guard.points} point(s)).`:''),critical?'crit':s.kind==='summon'?'summon':'spell');
}
async function dragonAction(type){if(type==='damage'||type==='heal'){if(!state.dragon){message('Dragon absent.');return}let n=await askNumber(type==='damage'?'Dégâts au dragon':'Soins du dragon',1,0,999);if(n===null)return;transaction(type==='damage'?'Dragon blessé':'Dragon soigné',()=>{let d=state.dragon,old=d.hp;d.hp=Math.min(d.max,Math.max(0,d.hp+(type==='heal'?n:-n)));let line=`${old} → ${d.hp}/${d.max} PV.`;if(!d.hp){state.dragon=null;state.sharedResistance='';state.concentration='';line+=' Invocation terminée.';if(state.phase==='dragon')state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return line});return}
 if(type==='dismiss'){if(!state.dragon)return;transaction('Dragon renvoyé',()=>{state.dragon=null;state.concentration='';state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return 'Concentration terminée.'});return}
 if(!state.dragon||state.phase!=='dragon'){message('Le dragon joue immédiatement après Samoth : terminez d’abord le tour de Samoth.');return}
 if(type==='dodge'){if(state.dragonEco.action){message('Action du dragon déjà utilisée.');return}transaction('Dragon · Esquive',()=>{state.dragonEco.action=true;return 'Les attaques contre le dragon ont désavantage jusqu’à son prochain tour.'});return}
 if(type==='rend'){if(state.dragonEco.rends>=2||state.dragonEco.action){message('Deux Déchirements maximum pendant son action multiple.');return}let ar=attackRoll(),r=await choose('Déchirement du dragon',`<p>${esc(ar.display)} +10 = <b>${ar.nat+10}</b>${ar.nat===20?' · critique':''}${ar.nat===1?' · échec automatique':''}</p><p>Touche ?</p>`,[{label:'Touché',value:'hit'},{label:'Raté',value:'miss'},{label:'Annuler',value:null}]);if(!r.choice)return;transaction('Dragon · Déchirement',()=>{state.dragonEco.rends++;let hit=ar.nat===20||ar.nat!==1&&r.choice==='hit',d=hit?damageDice(ar.nat===20?2:1,6):null,amount=hit?d.total+9:0;state.dragonDamage+=amount;return `${ar.nat}+10=${ar.nat+10} · ${hit?`${amount} perforants (${d.detail}+9)`:'raté'} · ${state.dragonEco.rends}/2 attaques.`});return}
 if(type==='breath'){if(state.dragonEco.breath||state.dragonEco.action){message('Souffle déjà utilisé.');return}let r=await choose('Souffle du dragon',`<label>Type <select name="type">${['froid','acide','feu','foudre','poison'].map(t=>`<option>${t}</option>`).join('')}</select></label><div class="field-row"><label>Échecs <input name="fail" type="number" min="0" value="1"></label><label>Réussites <input name="success" type="number" min="0" value="0"></label></div>`,[{label:'Résoudre',value:'go'},{label:'Annuler',value:null}]);if(!r.choice)return;let f=Number(r.data.fail),s=Number(r.data.success);if(!Number.isInteger(f)||!Number.isInteger(s)||f<0||s<0||f+s>50){message('Nombre de cibles invalide.');return}transaction('Dragon · Souffle',()=>{let d=damageDice(2,6,r.data.type==='froid'),amount=f*d.total+s*Math.floor(d.total/2);state.dragonEco.breath=true;state.dragonDamage+=amount;return `DEX DD18 · ${d.total} ${r.data.type} (${d.detail}) par échec, moitié en réussite · ${amount} dégâts cumulés.`})}
}
function stopConcentration(){if(!state.concentration)return;transaction('Concentration terminée',()=>{let prev=state.concentration;state.concentration='';state.dragon=null;state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return prev+' terminé ; invocation éventuelle disparue.'})}
async function useAbility(id){if(id==='restShort'||id==='restLong'){rest(id==='restLong');return}if(id==='radianceTick'){if(state.concentration!=='Rayonnement écœurant'){message('Rayonnement écœurant doit être maintenu.');return}let r=await choose('Exposition au rayonnement',`<div class="field-row"><label>Échecs <input name="fail" type="number" min="0" value="1"></label><label>Réussites <input name="success" type="number" min="0" value="0"></label></div>`,[{label:'Résoudre',value:'go'},{label:'Annuler',value:null}]);if(!r.choice)return;let f=Number(r.data.fail),s=Number(r.data.success);if(!Number.isInteger(f)||!Number.isInteger(s)||f<0||s<0||f+s>50){message('Nombre de cibles invalide.');return}transaction('Exposition au rayonnement',()=>{let d=damageDice(4,10),total=f*d.total;state.turnDamage+=total;return `CON DD18 · ${f} échec(s), ${s} réussite(s) · ${total} radiants (${d.detail}, ${d.total} par échec) et 1 épuisement par cible en échec. Aucun emplacement dépensé.`});return}if(id==='endConcentration'){stopConcentration();return}if(id==='flame'){transaction('Flammes de magie pure',()=>{if(!state.flame&&!state.flameArmed){message('Pouvoir déjà consommé aujourd’hui.');return false}state.flameArmed=!state.flameArmed;return state.flameArmed?'Prêt pour le prochain sort de niveau 1 ou plus qui inflige des dégâts.':'Déclenchement annulé.'});return}
 if(id==='wings'){if(!requireCost('reaction')||!state.wings){message('Réaction utilisée ou ailes épuisées.');return}transaction('Ailes protectrices',()=>{state.eco.reaction=true;state.wings--;return `+4 CA à Samoth ou un allié à 1,5 m contre une attaque ; ${state.wings}/4 usages restants.`});return}
 if(id==='slotToPoints'||id==='pointsToSlot'){if(!requireCost('bonus'))return;let level=Number($('#convertLevel').value);if(id==='slotToPoints'&&(!state.slots[level]||state.sp+level>10)){message('Emplacement absent ou capacité de 10 points de sorcellerie dépassée.');return}if(id==='pointsToSlot'&&(state.sp<SP_COST[level]||state.slots[level]>=MAX[level])){message('Points insuffisants ou maximum d’emplacements atteint.');return}transaction('Incantation flexible',()=>{state.eco.bonus=true;if(id==='slotToPoints'){state.slots[level]--;state.sp+=level;return `Emplacement N${level} converti en ${level} point(s).`}state.sp-=SP_COST[level];state.slots[level]++;return `${SP_COST[level]} points convertis en emplacement N${level}.`});return}
 if(id==='vial'){if(!state.vial||state.hitDice===10){message('La fiole exige des dés de vie dépensés, une fois par jour.');return}transaction('Fiole sanguine',()=>{state.vial=0;let amount=Math.min(5,10-state.sp);state.sp+=amount;return `+${amount} point(s) de sorcellerie, ${state.sp}/10.`});return}
 if(id==='resist'){if(state.sp<1){message('Il faut 1 point de sorcellerie ordinaire.');return}transaction('Affinité élémentaire',()=>{state.sp--;return 'Résistance au froid pendant 1 heure (1 SP consommé).'});return}
 if(id==='staff'||id==='staffVortex'){let n=id==='staffVortex'?3:1;if(!requireCost('action'))return;if(n>state.staff){message('Charges insuffisantes.');return}transaction('Bâton de confluence',()=>{state.staff-=n;state.eco.action=true;return `${id==='staffVortex'?'Vortex':'Mains'} : ${n} charge(s) dépensée(s), ${state.staff}/8 restantes. Effet exact à résoudre avec le MJ.`});return}
 if(id==='staffDawn'){transaction('Aube · bâton',()=>{let d=roll(4)+2,old=state.staff;state.staff=Math.min(8,state.staff+d);return `${old} → ${state.staff}/8 charges (récupération 1d4+2 = ${d}).`});return}
 if(id==='hitDice'){let n=await askNumber('Dés de vie à dépenser',1,1,state.hitDice);if(n===null)return;transaction('Dés de vie',()=>{let results=Array.from({length:n},()=>roll(6)+2),heal=results.reduce((a,b)=>a+b,0),old=state.hp;state.hp=Math.min(72,state.hp+heal);state.hitDice-=n;let vial='';if(state.vial&&state.sp<10){let gain=Math.min(5,10-state.sp);state.sp+=gain;state.vial=0;vial=` · Fiole sanguine : +${gain} SP (usage du jour consommé)`}return `${n}d6+${n*2} → ${heal} PV (${old} → ${state.hp}/72)${vial}.`});return}
 if(id==='feat'){transaction('Configuration · Adepte de métamagie',()=>{state.featEnabled=!state.featEnabled;state.featSp=state.featEnabled?2:0;return state.featEnabled?'Don activé : 2 points réservés à la métamagie.':'Don désactivé.'});return}
 if(id==='intensified'){transaction('Configuration · Sort intensifié',()=>{state.intensified=!state.intensified;if(!state.intensified&&state.meta==='heighten')state.meta='none';return state.intensified?'Option autorisée par le MJ.':'Option désactivée.'});return}}
function nextTurn(){transaction('Tour suivant',()=>{if(state.phase==='samoth'&&state.dragon){state.phase='dragon';state.dragonEco={action:false,move:false,rends:0,breath:false};state.dragonDamage=0;return 'Tour du dragon immédiatement après Samoth.'}let dodge=state.phase==='dragon'&&state.dragon&&!state.dragonEco.rends&&!state.dragonEco.breath&&!state.dragonEco.action;state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.turnDamage=0;state.bonusSpell=false;state.leveledAction=false;return `${dodge?'Le dragon sans ordre a esquivé. ':''}Round ${state.round} · économie de Samoth restaurée ; concentration maintenue.`});if(state.phase==='dragon')view('dragon');else view('combat')}
function rest(long){if(!confirm(`Effectuer un repos ${long?'long':'court'} ?`))return;transaction(long?'Repos long':'Repos court',()=>{if(!long)return 'Les emplacements et points de sorcellerie ne reviennent pas. Dépensez les dés de vie avec le bouton Ressources ; la fiole s’active automatiquement.';let old=state.hp;state.hp=72;state.tempHp=0;state.slots={...MAX};state.sp=10;state.featSp=state.featEnabled?2:0;state.hitDice=Math.min(10,state.hitDice+5);state.cureFree=1;state.wings=4;state.flame=1;state.flameArmed=false;state.vial=1;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false;state.concentration='';state.dragon=null;state.sharedResistance='';state.phase='samoth';return `PV ${old} → 72, emplacements et sorcellerie restaurés, +5 dés de vie maximum, usages journaliers remis. Bâton : récupération à l’aube séparée.`})}
function view(id){$$('.view').forEach(e=>e.classList.toggle('active',e.id===id));$$('.nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===id));window.scrollTo({top:0,behavior:'instant'})}
function render(){const d=state.dragon,dragonPhase=state.phase==='dragon';$('#hp').value=state.hp;$('#tempHp').value=state.tempHp||'';$('#round').textContent=state.round;$('#actor').textContent=dragonPhase?'Dragon':'Samoth';$('#damageTurn').textContent=dragonPhase?state.dragonDamage:state.turnDamage;$('#damageActor').textContent=dragonPhase?'par le dragon':'par Samoth';$('#concText').textContent=state.concentration||'Aucune';$('#concButton').classList.toggle('used',!state.concentration);$('#nextTurn').textContent=dragonPhase?'Fin du tour du dragon ›':d?'Tour du dragon ›':'Round suivant ›';$('#undo').disabled=!state.undo;
 $$('[data-econ]').forEach(b=>{let key=b.dataset.econ,used=dragonPhase?(key==='action'?state.dragonEco.action||state.dragonEco.rends>=2&&state.dragonEco.breath:key==='move'?state.dragonEco.move:key==='reaction'?state.eco.reaction:false):state.eco[key];b.classList.toggle('used',!!used);b.querySelector('small').textContent=used?'Utilisée':key==='move'?(dragonPhase?'9 / 18 m':'9 m'):'Libre';b.disabled=dragonPhase&&key==='bonus'});
 $$('[data-cast]').forEach(b=>{let s=getSpell(b.dataset.cast);if(!s)return;let cost=s.kind==='reaction'?'reaction':state.meta==='quick'?'bonus':'action',blocked=dragonPhase||state.eco[cost]||(s.lv&&!(s.id==='cure'&&state.cureFree)&&!Object.keys(MAX).some(n=>Number(n)>=s.lv&&state.slots[n]>0))||cost==='action'&&state.bonusSpell&&s.lv>0||cost==='bonus'&&state.leveledAction;b.disabled=!!blocked;b.title=blocked?'Tour ou ressource indisponible':''});
 $$('[data-ability="wings"]').forEach(b=>b.disabled=state.eco.reaction||!state.wings);
 $('[data-ability="radianceTick"]').disabled=state.concentration!=='Rayonnement écœurant';$('#combatSummary').textContent=`${state.hp}/72 PV · ${state.tempHp} temporaires · ${state.sp}/10 points de sorcellerie${state.featEnabled?` + ${state.featSp}/2 dédiés`:''} · ${state.concentration||'sans concentration'}${state.flameArmed?' · flammes pures prêtes':''}.`;
 $('#dragonStatus').textContent=d?`· ${d.hp}/${d.max} PV`:'· non invoqué';$('#dragonResistance').textContent=d?`Résistance partagée : ${state.sharedResistance}.`:'La convocation exige un emplacement N5 et la concentration.';$('#dragonTurnState').textContent=d?`${dragonPhase?'À jouer maintenant':'Attend son tour'} · Déchirements ${state.dragonEco.rends}/2 · Souffle ${state.dragonEco.breath?'utilisé':'libre'} · ${state.dragonDamage} dégâts ce tour.`:'Invoquez-le depuis Combat ou Sorts.';
 $$('[data-dragon="rend"],[data-dragon="breath"],[data-dragon="dodge"]').forEach(b=>b.disabled=!d||!dragonPhase||state.dragonEco.action||(b.dataset.dragon==='rend'&&state.dragonEco.rends>=2)||(b.dataset.dragon==='breath'&&state.dragonEco.breath)||(b.dataset.dragon==='dodge'&&(state.dragonEco.rends>0||state.dragonEco.breath)));
 renderResources();renderSpellList();renderInventory();renderHistory();}
function renderResources(){let body=Object.keys(MAX).map(n=>`<div class="resource-line"><span>Emplacements N${n}</span><strong>${state.slots[n]}/${MAX[n]}</strong></div>`).join('');$('#resourcesBody').innerHTML=body+`<div class="resource-line"><span>Points de sorcellerie</span><strong>${state.sp}/10</strong></div><div class="resource-line"><span>Adepte de métamagie (option)</span><button class="ability" data-ability="feat">${state.featEnabled?'Activé · '+state.featSp+'/2':'Désactivé'}</button></div><div class="resource-line"><span>Dés de vie d6</span><strong>${state.hitDice}/10</strong><button class="ability" data-ability="hitDice">Dépenser</button></div>`;
 $('#metaBody').innerHTML=`<p class="meta">Sélectionner avant de lancer le sort. Renforcé relance automatiquement jusqu’à 3 dés les plus faibles.</p>${[['none','Aucune'],['quick','Accéléré · 2 SP'],['twin','Jumeau · coût niveau'],['empower','Renforcé · 1 SP'],...(state.intensified?[['heighten','Intensifié · 3 SP']]:[])].map(([k,v])=>`<button class="ability ${state.meta===k?'selected':''}" data-meta="${k}">${v}</button>`).join('')}<div class="resource-line">Intensifié (validation MJ) <button class="ability" data-ability="intensified">${state.intensified?'Autorisé':'Désactivé'}</button></div>`;
 $('#convertLevel').innerHTML=Object.keys(MAX).map(n=>`<option value="${n}">Niveau ${n} · coût ${SP_COST[n]} SP</option>`).join('');$('#chargesBody').innerHTML=`<div class="resource-line">Soins gratuit <strong>${state.cureFree}/1</strong></div><div class="resource-line">Ailes protectrices <strong>${state.wings}/4</strong></div><div class="resource-line">Flammes pures <strong>${state.flame}/1</strong></div><div class="resource-line">Bâton <strong>${state.staff}/8</strong></div><div class="list"><button class="ability" data-ability="staff">Mains · 1 charge / action</button><button class="ability" data-ability="staffVortex">Vortex · 3 charges / action</button><button class="ability" data-ability="staffDawn">Aube · récupérer charges</button><button class="ability" data-ability="resist">Résistance au froid · 1 SP</button></div>`}
function renderSpellList(){let lv=-1;$('#spellList').innerHTML=SPELLS.map(s=>{let header=s.lv!==lv?`<h2 class="section-label" style="grid-column:1/-1">${s.lv?'Niveau '+s.lv:'Tours de magie'}</h2>`:'';lv=s.lv;return header+`<article class="spell"><h3>${esc(s.name)}</h3><p class="meta">${s.kind==='reaction'?'Réaction':'Action'} · ${esc(s.range)}${s.concentration?' · concentration':''}</p><button class="primary" data-cast="${s.id}">Lancer${s.id==='cure'&&state.cureFree?' · gratuit disponible':''}</button><details class="spell-doc"><summary>Effet et composantes</summary><div class="spell-doc-body"><b>V, S, M :</b> ${esc(s.components)}<br><b>Durée :</b> ${esc(s.duration||'Instantanée')}<br>${esc(s.desc)}</div></details></article>`}).join('')}
const SOCIAL={Caractéristiques:{FOR:[8,-1],DEX:[13,1],CON:[14,2],INT:[12,1],SAG:[10,0],CHA:[17,3]},'Jets de sauvegarde':{FOR:-1,DEX:1,CON:6,INT:1,SAG:0,CHA:7},Compétences:{Athlétisme:-1,Acrobaties:1,Discrétion:1,Escamotage:1,Arcanes:5,Histoire:1,Investigation:1,Nature:1,Religion:5,Dressage:0,Intuition:4,Médecine:0,Perception:0,Survie:0,Intimidation:7,Persuasion:7,Représentation:3,Tromperie:7}};
function renderSocial(){let container=$('#socialBody');container.innerHTML=Object.entries(SOCIAL).map(([name,values])=>`<article class="card ${name==='Compétences'?'wide':''}"><h2>${name}</h2><div class="social-row">${Object.entries(values).map(([key,val])=>{let bonus=Array.isArray(val)?val[1]:val;return `<button class="ability" data-roll="${esc(name)} · ${esc(key)}" data-bonus="${bonus}"><span>${esc(key)}${Array.isArray(val)?` (${val[0]})`:''}</span><b>${bonus>=0?'+':''}${bonus}</b></button>`}).join('')}</div></article>`).join('')+`<article class="card"><h2>Traits et langues</h2><p>Commun, elfique, géant, orc, draconique, primordial. Vision dans le noir 18 m. Ascendance féerique : avantage aux JDS contre charme ; la magie ne peut pas endormir Samoth.</p><p>Perception passive 10 · Intuition passive 14 · Investigation passive 11.</p></article>`}
function renderInventory(){let area=$('#itemsBody');area.innerHTML=['equipment','misc'].map(cat=>`<h3 class="section-label">${cat==='equipment'?'Équipements':'Objets divers et consommables'}</h3>${state.items.filter(i=>i.category===cat).map(i=>`<div class="item-row">${i.image&&/^(https:\/\/|data:image\/)/.test(i.image)?`<img src="${esc(i.image)}" alt="">`:'<span aria-hidden="true">❄</span>'}<div><b>${esc(i.name)}</b> ×${i.qty}${i.equipped?' · équipé':''}<p>${esc(i.note)}</p></div><button class="ability" data-item="${esc(i.id)}">Modifier</button>${i.qty>0?`<button class="ability" data-use="${esc(i.id)}">Utiliser</button>`:''}</div>`).join('')||'<p class="meta">Aucun objet.</p>'}`).join('')}
function renderHistory(){let logs=state.history;$('#journalBody').innerHTML=logs.length?logs.slice(0,70).map(e=>`<div class="log-entry"><small>${esc(new Date(e.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))} · round ${e.round} · ${esc(e.actor)}</small><br><b>${esc(e.title)}</b><div>${esc(e.detail)}</div></div>`).join(''):'<p class="meta">Aucune action enregistrée.</p>';$('#npcBody').innerHTML=state.npcs.map((n,i)=>`<div class="npc-row">${n.image&&/^(https:\/\/|data:image\/)/.test(n.image)?`<img src="${esc(n.image)}" alt="">`:''}<div><b>${esc(n.name)}</b><p>${esc(n.note)}</p></div><button class="ability" data-npc="${i}">Modifier</button><button class="ability danger" data-npc-remove="${i}">×</button></div>`).join('');$('#preview').textContent=state.notes||'Aucune note.';$('#notesPreview').open=state.preview}
async function itemEditor(id){let old=state.items.find(i=>i.id===id),data=await askText(old?'Modifier un objet':'Ajouter un objet',[{key:'name',label:'Nom',max:160},{key:'qty',label:'Quantité',type:'number'},{key:'note',label:'Description / notes',type:'textarea'},{key:'image',label:'Image HTTPS (ou choisir un fichier après enregistrement)'}],old||{qty:1});if(!data)return;let qty=Number(data.qty);if(!data.name.trim()||!Number.isInteger(qty)||qty<0||qty>9999){message('Nom ou quantité invalide.');return}let category=old?.category||'misc',equipped=old?.equipped||false;let c=await choose('Catégorie et port',`<label>Catégorie <select name="category"><option value="equipment" ${category==='equipment'?'selected':''}>Équipement</option><option value="misc" ${category==='misc'?'selected':''}>Divers / consommable</option></select></label><label>Équipé <select name="equipped"><option value="no">Non</option><option value="yes" ${equipped?'selected':''}>Oui</option></select></label>`,[{label:'Valider',value:'ok'},{label:'Annuler',value:null}]);if(!c.choice)return;let obj={id:old?.id||crypto.randomUUID(),name:data.name.trim().slice(0,160),qty,note:data.note.slice(0,5000),image:/^(https:\/\/|data:image\/)/.test(data.image)?data.image:old?.image||'',category:c.data.category,equipped:c.data.equipped==='yes'};transaction(old?'Objet modifié':'Objet ajouté',()=>{if(old)state.items[state.items.indexOf(old)]=obj;else state.items.push(obj);return `${obj.name} ×${obj.qty}.`});let p=await choose('Image de l’objet',`<p>Ajouter une icône locale ou supprimer l’objet ?</p>`,[{label:'Choisir une image',value:'image'},...(old?[{label:'Supprimer l’objet',value:'delete'}]:[]),{label:'Terminer',value:null}]);if(p.choice==='image'){$('#imageInput').dataset.item=obj.id;$('#imageInput').click()}if(p.choice==='delete'&&confirm('Supprimer cet objet ?'))transaction('Objet supprimé',()=>{state.items=state.items.filter(i=>i.id!==obj.id);return obj.name})}
function download(name,body,type='application/json'){let url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function npcEditor(index){let old=state.npcs[index]||{},data=await askText(old.name?'Modifier le PNJ':'Ajouter un PNJ',[{key:'name',label:'Nom',max:160},{key:'note',label:'Notes',type:'textarea'},{key:'image',label:'Image HTTPS'}],old);if(!data||!data.name.trim())return;let npc={name:data.name.trim().slice(0,160),note:data.note.slice(0,5000),image:/^https:\/\//.test(data.image)?data.image:''};transaction('Fiche PNJ',()=>{if(index>=0)state.npcs[index]=npc;else state.npcs.push(npc);return npc.name})}
$('#notes').value=state.notes;if(loadError)message(loadError);renderSocial();render();
$$('.nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#nextTurn').onclick=nextTurn;$('#shortRest').onclick=()=>rest(false);$('#longRest').onclick=()=>rest(true);$('#resultClose').onclick=()=>$('#result').hidden=true;$('#concButton').onclick=()=>state.concentration?stopConcentration():view('spells');$('#undo').onclick=()=>{if(!state.undo)return;let prev=clone(state.undo);prev.undo=null;state=prev;persist();render();message('Dernière opération annulée ; ressources et journal restaurés.')};
$('#hp').onchange=e=>{let n=Number(e.target.value);if(!Number.isFinite(n)||n<0||n>72){render();return}transaction('PV ajustés',()=>{let old=state.hp;state.hp=n;return `${old} → ${n}/72.`})};$('#tempHp').onchange=e=>{let n=Number(e.target.value);if(!Number.isFinite(n)||n<0||n>999){render();return}transaction('PV temporaires ajustés',()=>{state.tempHp=n;return `${n} PV temporaires.`})};
$('#notes').oninput=e=>{state.notes=e.target.value;$('#preview').textContent=state.notes||'Aucune note.';persist()};$('#notesPreview').ontoggle=e=>{state.preview=e.target.open;persist()};
$('#addItem').onclick=()=>itemEditor();$('#addNpc').onclick=()=>npcEditor(-1);$('#export').onclick=()=>download('samoth-companion-v3.json',JSON.stringify({format:'samoth-companion-v3',schema:3,state:{...state,undo:null}},null,2));$('#import').onclick=()=>$('#fileInput').click();$('#reset').onclick=()=>{if(!confirm('Effacer la partie de Samoth, inventaire et notes compris ? Exportez-la d’abord si besoin.'))return;let previous=localStorage.getItem(KEY);try{localStorage.setItem(KEY+':backup',previous||'');state=fresh();persist();location.reload()}catch{message('Remise à zéro impossible.')}};
$('#fileInput').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>2500000)throw Error('Fichier trop volumineux.');let doc=JSON.parse(await file.text());if(doc.format!=='samoth-companion-v3'||doc.schema!==3||!doc.state||!Array.isArray(doc.state.items)||!Array.isArray(doc.state.history)||!doc.state.slots||!doc.state.eco||!Number.isFinite(doc.state.hp))throw Error('Sauvegarde Samoth V3 invalide.');if(!confirm('Remplacer la partie actuelle ? Une copie sera conservée localement.'))return;localStorage.setItem(KEY+':backup',localStorage.getItem(KEY)||'');state={...doc.state,undo:null};persist();location.reload()}catch(err){message(err.message)}finally{e.target.value=''}};
$('#imageInput').onchange=async e=>{let f=e.target.files[0],id=e.target.dataset.item;if(!f)return;if(!f.type.startsWith('image/')||f.size>160000){message('Image requise, 160 Ko maximum pour préserver le stockage local.');return}let url=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});transaction('Icône ajoutée',()=>{let item=state.items.find(i=>i.id===id);if(!item)return false;item.image=url;return item.name});e.target.value=''};
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.cast){await cast(b.dataset.cast);return}if(b.dataset.dragon){await dragonAction(b.dataset.dragon);return}if(b.dataset.ability){await useAbility(b.dataset.ability);return}if(b.dataset.meta){state.meta=b.dataset.meta;persist();render();return}if(b.dataset.rollmode){$$('[data-rollmode]').forEach(x=>x.classList.toggle('on',x===b));return}if(b.dataset.econ){let key=b.dataset.econ;if(state.phase==='dragon'&&key==='bonus')return;transaction('Économie du tour',()=>{let eco=state.phase==='dragon'?state.dragonEco:state.eco;eco[key]=!eco[key];return `${key} ${eco[key]?'utilisé':'restauré manuellement'}.`});return}if(b.dataset.hp){let n=await askNumber(b.dataset.hp==='damage'?'Dégâts subis':'Soins reçus',1,0,999);if(n===null)return;transaction(b.dataset.hp==='damage'?'Dégâts reçus':'Soins reçus',()=>{let old=state.hp,t=state.tempHp;if(b.dataset.hp==='damage'){let absorbed=Math.min(t,n);state.tempHp-=absorbed;state.hp=Math.max(0,state.hp-(n-absorbed))}else state.hp=Math.min(72,state.hp+n);let check='';if(b.dataset.hp==='damage'&&state.concentration&&n>0){let dc=Math.max(10,Math.floor(n/2)),natural=roll(20),total=natural+6;check=` · Concentration CON ${natural}+6=${total} contre DD${dc}`;if(total<dc){check+=' : perdue';state.concentration='';state.dragon=null;state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}}else check+=' : maintenue'}return `${n} ${b.dataset.hp==='damage'?'dégâts':'PV de soins'} · PV ${old}→${state.hp}/72, temporaires ${t}→${state.tempHp}${check}.`});return}if(b.dataset.roll){let n=roll(20),bonus=Number(b.dataset.bonus),text=`d20 ${n} ${bonus>=0?'+':'−'}${Math.abs(bonus)} = ${n+bonus}${n===1?' · 1 naturel':n===20?' · 20 naturel':''}`;transaction(b.dataset.roll,()=>text);return}if(b.dataset.item){await itemEditor(b.dataset.item);return}if(b.dataset.use){let item=state.items.find(i=>i.id===b.dataset.use);if(item&&item.qty)transaction('Objet utilisé',()=>{item.qty--;return `${item.name} · ${item.qty} restant(s). Effet à appliquer selon l’objet.`});return}if(b.dataset.npc){await npcEditor(Number(b.dataset.npc));return}if(b.dataset.npcRemove&&confirm('Supprimer ce PNJ ?'))transaction('PNJ supprimé',()=>{let n=state.npcs.splice(Number(b.dataset.npcRemove),1)[0];return n?.name||''})});
