'use strict';
/* Samoth Companion V3. One canonical state, one transaction per committed action. */
const KEY='samoth-companion-v3',MAX={1:4,2:3,3:3,4:3,5:2},SP_COST={1:2,2:3,3:5,4:6,5:7};
const SPELLS=[
{id:'rayon',name:'Rayon de givre',lv:0,kind:'attack',dice:[2,8],cold:true,range:'18 m',components:'V, S',desc:'Attaque +10. Touché : froid, vitesse de la cible réduite de 3 m jusqu’au début du prochain tour.',twin:true},
{id:'water',name:'Façonnage de l’eau',lv:0,range:'9 m',components:'S',duration:'Instantané ou 1 h',desc:'Déplacer, colorer, façonner ou geler un cube de 1,5 m d’eau ; deux effets non instantanés.'},
{id:'frostbite',name:'Gelure',lv:0,kind:'save',save:'CON',dice:[2,6],cold:true,twin:true,range:'18 m',components:'V, S',desc:'Échec au JDS : froid et désavantage à la prochaine attaque avec arme avant la fin du prochain tour.'},
{id:'illusion',name:'Illusion mineure',lv:0,range:'9 m',components:'S, M',duration:'1 min',desc:'Son ou image dans un cube de 1,5 m ; interaction physique révèle l’illusion.'},
{id:'magehand',name:'Main de mage',lv:0,range:'9 m',components:'V, S',duration:'1 min',desc:'Manipuler à distance un objet de 5 kg maximum, sans attaque ni objet magique.'},
{id:'prestidigitation',name:'Prestidigitation',lv:0,range:'3 m',components:'V, S',duration:'Jusqu’à 1 h',desc:'Effets magiques mineurs ; jusqu’à trois effets persistants simultanément.'},
{id:'absorb',name:'Absorption des éléments',lv:1,kind:'reaction',range:'Personnelle',components:'S',duration:'1 round',desc:'Résistance temporaire à acide, froid, feu, foudre ou tonnerre ; +1d6 du type absorbé sur le premier toucher au corps à corps suivant.'},
{id:'missile',name:'Projectile magique',lv:1,kind:'automatic',range:'36 m',components:'V, S',desc:'Trois projectiles automatiques de 1d4+1 force, +1 projectile par niveau supérieur.'},
{id:'shield',name:'Bouclier',lv:1,kind:'reaction',range:'Personnelle',components:'V, S',duration:'1 round',desc:'+5 CA jusqu’au début de votre prochain tour ; annule Projectile magique contre vous.'},
{id:'orb',name:'Orbe chromatique',lv:1,kind:'attack',dice:[3,8],range:'27 m',components:'V, S, M',twin:true,desc:'Attaque +10 ; 3d8 du type choisi, +1d8 par niveau supérieur. Choisir froid pour la spécialisation.'},
{id:'cure',name:'Soins',lv:1,kind:'heal',twin:true,range:'Contact',components:'V, S',desc:'1d8+3 PV, +1d8 par niveau supérieur ; une utilisation gratuite par repos long grâce au Présent du dragon métallique.'},
{id:'haste',name:'Hâte',lv:3,concentration:true,twin:true,range:'9 m',components:'V, S, M',duration:'10 rounds',desc:'+2 CA, avantage JDS DEX, vitesse doublée et action supplémentaire limitée. Léthargie un tour à la fin.'},
{id:'counter',name:'Contresort',lv:3,kind:'reaction',range:'18 m',components:'S',desc:'Interruption automatique si niveau du sort cible ≤ niveau de l’emplacement ; sinon test de Charisme +7, DD 10 + niveau ciblé.'},
{id:'vortex',name:'Vortex de glace',lv:3,kind:'save',save:'DEX',dice:[8,6],cold:true,half:true,range:'45 m',components:'V, S, M',desc:'Sphère rayon 6 m ; 8d6 froid, moitié en réussite, +1d6 par niveau supérieur. Adaptation maison de Boule de feu.'},
{id:'invisibility',name:'Invisibilité supérieure',lv:4,concentration:true,twin:true,range:'Contact',components:'V, S',duration:'10 rounds',desc:'Invisible même après une attaque ou une incantation.'},
{id:'radiance',name:'Rayonnement écœurant',lv:4,concentration:true,range:'36 m',components:'V, S',duration:'10 min',desc:'Sphère rayon 9 m ; CON DD18, 4d10 radiant et un épuisement en échec à chaque exposition.'},
{id:'storm',name:'Tempête de grêle',lv:4,kind:'storm',save:'DEX',half:true,range:'90 m',components:'V, S, M',desc:'Cylindre rayon 6 m ; 2d8 contondant +4d6 froid, moitié en réussite. Terrain difficile un tour.'},
{id:'cone',name:'Cône de froid',lv:5,kind:'save',save:'CON',dice:[8,8],cold:true,half:true,range:'Cône 18 m',components:'V, S, M',desc:'8d8 froid, moitié en réussite ; +1d8 par niveau supérieur.'},
{id:'dragon',name:'Convocation d’esprit draconique',lv:5,kind:'summon',concentration:true,range:'18 m',components:'V, S, M (objet gravé ≥500 po)',duration:'1 h',desc:'Esprit métallique d’argent, CA19, PV50. Deux Déchirements et Souffle ; agit après Samoth.'}
];
const STAFF_SPELLS={
hands:{id:'hands',name:'Mains givrantes',cost:1,save:'CON',kind:'save',dice:[2,8],cold:true,half:true,desc:'Cône glacé à courte portée. Échec : dégâts de froid ; réussite : moitié.'},
fog:{id:'fog',name:'Nappe de brouillard',cost:1,kind:'utility',concentration:true,desc:'Crée une zone de brouillard fortement obscurcie. Concentration.'},
vortex:{id:'vortex',name:'Vortex de glace',cost:3,save:'DEX',kind:'save',dice:[8,6],cold:true,half:true,desc:'Le Vortex peut être lancé soit avec 3 charges du bâton, soit avec un emplacement de sort.'},
storm:{id:'storm',name:'Tempête de grêle',cost:4,save:'DEX',kind:'storm',cold:true,half:true,desc:'2d8 contondant + 4d6 froid ; réussite : moitié ; terrain difficile.'},
cone:{id:'cone',name:'Cône de froid',cost:5,save:'CON',kind:'save',dice:[8,8],cold:true,half:true,desc:'8d8 froid ; réussite : moitié.'},
wall:{id:'wall',name:'Mur de glace',cost:4,kind:'utility',concentration:true,desc:'Dresse un mur de glace. Les effets exacts de zone et de dégâts sont résolus à la table.'}
};
const STAFF_ONLY=new Set(['storm','cone']);
const SPELL_SOURCE={rayon:'rayon-de-givre',water:'faconnage-de-l-eau',frostbite:'gelure',illusion:'illusion-mineure',magehand:'main-de-mage',prestidigitation:'prestidigitation',absorb:'absorption-des-elements',missile:'projectile-magique',shield:'bouclier',orb:'orbe-chromatique',cure:'soins',haste:'hate',counter:'contresort',vortex:'boule-de-feu',invisibility:'invisibilite-superieure',radiance:'rayonnement-ecoeurant',storm:'tempete-de-grele',cone:'cone-de-froid',dragon:'convocation-d-esprit-draconique'};
const SPELL_ROLES={froid:['rayon','frostbite','vortex','storm','cone'],defense:['absorb','shield','counter'],soin:['cure'],invocation:['dragon'],soutien:['haste','invisibility'],controle:['radiance','illusion'],arcane:['missile','orb','water','magehand','prestidigitation']};
const ROLE_LABEL={froid:'Givre · dégâts',defense:'Défense · réaction',soin:'Soins',invocation:'Invocation',soutien:'Soutien · concentration',controle:'Contrôle',arcane:'Arcanes'};
const spellRole=s=>Object.keys(SPELL_ROLES).find(role=>SPELL_ROLES[role].includes(s.id))||'arcane';
const initialItems=[
['Bâton de confluence','equipment',1,'8 charges. Mains givrantes 1, Nappe de brouillard 1, Vortex de glace 3, Tempête de grêle 4, Cône de froid 5, Mur de glace 4 ; récupère 1d4+2 charges à l’aube.'],
['Broche protectrice','equipment',1,'Broche équipée : +1 CA. CA de Samoth portée à 15.'],['Dague','equipment',2,'+4, 1d4+1 perforant.'],['Fiole sanguine','equipment',1,'Liée : +2 à l’attaque de sort et au DD déjà intégrés ; +5 SP une fois/jour si dé de vie dépensé.'],['Anneau de chaleur constante','equipment',1,'Effet à confirmer à la table.'],['Anneau de transplanation chaotique','equipment',1,'Effet à confirmer à la table.'],['Anneau en bois','equipment',1,'Régénération 1d6 PV par heure selon validation du MJ.'],['Potion de soin mineur','misc',6,'Consommable ; montant des soins selon le MJ.'],['Potion de soin majeur','misc',2,'Consommable ; montant des soins selon le MJ.'],['Potion d’immunité au froid','misc',1,'Consommable.'],['Potion de résistance tonnerre','misc',1,'Consommable.'],['Antivenin','misc',1,'Consommable.']].map(([name,category,qty,note])=>({id:crypto.randomUUID(),name,category,qty,note,image:'',equipped:category==='equipment'}));
function fresh(){return{schema:3,hp:72,tempHp:0,rollMode:'normal',round:1,phase:'samoth',eco:{action:false,bonus:false,reaction:false,move:false},dragonEco:{action:false,move:false,rends:0,breath:false},turnDamage:0,dragonDamage:0,slots:{...MAX},sp:10,featSp:0,featEnabled:false,intensified:false,concentration:'',dragon:null,sharedResistance:'',cureFree:1,wings:4,flame:1,flameArmed:false,vial:1,staff:8,hitDice:10,bonusSpell:false,leveledAction:false,meta:'none',selectedSpell:'rayon',history:[],notes:'',npcs:[],items:structuredClone(initialItems),preview:true,undo:null};}
function migrateOld(){let oldRaw=localStorage.getItem('samoth-v3');if(!oldRaw)return fresh();let old=JSON.parse(oldRaw);if(old.schema!==3||!Number.isFinite(old.hp)||!old.slots)throw Error('Ancien combat incompatible');let next=fresh();next.hp=Math.max(0,Math.min(72,old.hp));next.tempHp=Math.max(0,old.tempHp||0);next.slots={...MAX,...old.slots};next.sp=Math.max(0,Math.min(10,old.spCore??10));next.featEnabled=Number.isFinite(old.spBonus)||Number.isFinite(old.spMeta);next.featSp=next.featEnabled?Math.max(0,Math.min(2,old.spBonus??old.spMeta??2)):0;next.concentration=old.concentration||old.conc||'';next.dragon=old.dragon?{hp:old.dragonHp||50,max:50,ac:19,level:5}:null;next.phase=old.phase==='dragon'&&next.dragon?'dragon':'samoth';next.round=old.round||1;next.eco={...next.eco,...old.eco};next.wings=old.wings??4;next.cureFree=old.freeHeal??1;next.flame=old.pure??1;next.flameArmed=!!old.pureArmed;next.vial=old.vial??1;next.staff=old.staff??8;next.turnDamage=old.turnDamage||0;next.history=(old.journal||[]).slice(0,150).map(e=>({at:new Date().toISOString(),round:e.round||1,actor:'samoth',title:e.title||'Ancien événement',detail:e.detail||'',kind:e.type||'action'}));let surfacesRaw=localStorage.getItem('companion-v3:samoth:'+location.pathname.replace(/index\.html$/,''));if(surfacesRaw){let x=JSON.parse(surfacesRaw);if(x.schema===1){next.items=(x.items||[]).map(i=>({...i,id:crypto.randomUUID(),category:i.category==='equipment'?'equipment':'misc',equipped:!!i.active}));next.notes=x.notes||'';next.npcs=x.npcs||[];next.preview=x.preview??true}}return next}
let state;let loadError='';try{let raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):migrateOld();if(state.schema!==3||!Array.isArray(state.history)||!Array.isArray(state.items)||!state.slots||!state.eco)throw Error('Sauvegarde incompatible');}catch(e){state=fresh();loadError='Ancienne sauvegarde illisible conservée : exportez-la depuis le stockage du navigateur avant remise à zéro.';}
if(!['normal','adv','dis'].includes(state.rollMode))state.rollMode='normal';
if(!state.items.some(i=>/broche protectrice/i.test(i.name))){state.items.push({id:crypto.randomUUID(),name:'Broche protectrice',category:'equipment',qty:1,note:'Broche équipée : +1 CA. CA de Samoth portée à 15.',image:'',equipped:true});persist?.();}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>structuredClone(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let castDraft={};
function draftFor(s){return castDraft[s.id]??={level:s.lv||0,fail:1,success:0,element:'froid',resistance:'froid',free:s.id==='cure'&&!!state.cureFree,useStaff:STAFF_ONLY.has(s.id)}}
function readCastDraft(s){let d=draftFor(s);$$('#castSetup [data-cast-field]').forEach(el=>{if(el.dataset.castField==='free'){d.free=el.value==='free';d.level=d.free?1:Number(el.value)}else if(el.type==='checkbox')d[el.dataset.castField]=el.checked;else d[el.dataset.castField]=el.type==='number'?Number(el.value):el.value});return d}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));queueMicrotask(()=>window.CompanionAPI?.sync());return true}catch(e){message('Stockage saturé : exportez votre partie (images locales volumineuses).');return false}}
function roll(sides){return Math.floor(Math.random()*sides)+1}
function dice(n,s,cold=false){let raw=Array.from({length:n},()=>roll(s));return{raw,values:raw.map(v=>cold&&v===1?2:v),get total(){return this.values.reduce((a,b)=>a+b,0)}}}
function damageDice(n,s,cold=false,empowered=false){let d=dice(n,s,cold),before=[...d.values];if(empowered){let indexes=d.values.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]).slice(0,3);for(let[,i]of indexes){d.raw[i]=roll(s);d.values[i]=cold&&d.raw[i]===1?2:d.raw[i]}}return{total:d.total,detail:d.values.join('+')+(empowered?' [relance '+before.join('+')+']':'')}}
let resultTimer;function message(msg){let lines=String(msg).split('\n');$('#resultTitle').textContent=lines.shift()||'Dernier résultat';$('#resultText').textContent=lines.join(' · ')||'Action enregistrée.';$('#result').classList.remove('collapsed');clearTimeout(resultTimer);resultTimer=setTimeout(()=>$('#result').classList.add('collapsed'),3800)}
function effect(kind,level=0){
 if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const stage=document.querySelector('#samothFx');if(!stage)return;
 const summon=kind==='summon',major=summon||kind==='crit'||level>=5,scale=Math.max(1,Math.min(2.25,1+level*.24));
 const palette=kind==='meta'?'#b7b2ff':kind==='flame'?'#ffd0a3':'#9feaff';
 stage.className='samoth-fx '+kind;stage.replaceChildren();stage.style.setProperty('--glow',palette);stage.style.setProperty('--scale',scale);
 const rune=document.createElement('div');rune.className='fx-rune';stage.append(rune);
 const shock=document.createElement('div');shock.className='fx-shockwave';stage.append(shock);
 const mist=document.createElement('div');mist.className='fx-mist';stage.append(mist);
 if(summon){const dragon=document.createElement('div');dragon.className='frost-dragon';dragon.innerHTML='<svg viewBox="0 0 900 620" aria-hidden="true"><path class="dragon-wing left" d="M427 319 Q292 68 31 124 Q164 178 159 290 Q241 258 345 359Z"/><path class="dragon-wing right" d="M473 319 Q608 68 869 124 Q736 178 741 290 Q659 258 555 359Z"/><path class="dragon-body" d="M430 272 Q356 295 365 398 Q392 490 450 580 Q508 490 535 398 Q544 295 470 272 L520 158 L486 184 L450 56 L414 184 L380 158Z"/><path class="dragon-head" d="M406 266 L372 218 L414 231 L450 188 L486 231 L528 218 L494 266 L500 330 L464 310 L450 360 L436 310 L400 330Z"/><path class="dragon-ridge" d="M450 75 L450 580 M370 220 Q450 270 530 220"/></svg><span class="dragon-summon-label">ESPRIT DRACONIQUE · ARGENT</span>';stage.append(dragon)}
 if(['vortex','storm','cone','hands','fog','wall','rayon','frostbite','breath','cold','crit'].includes(kind)){const form=document.createElement('div');form.className='frost-form';stage.append(form)}
 const count=summon?96:Math.round((major?46:18)+level*8);
 for(let i=0;i<count;i++){const shard=document.createElement('i');const angle=Math.random()*Math.PI*2,span=(major?330:145)*scale*(.45+Math.random());shard.style.setProperty('--x',Math.cos(angle)*span+'px');shard.style.setProperty('--y',Math.sin(angle)*span+'px');shard.style.setProperty('--delay',(Math.random()*(summon?.62:.28))+'s');shard.style.setProperty('--size',(3+Math.random()*10*scale)+'px');stage.append(shard)}
 stage.classList.remove('play');void stage.offsetWidth;stage.classList.add('play');clearTimeout(effect.timer);effect.timer=setTimeout(()=>{stage.classList.remove('play');stage.replaceChildren()},summon?3900:major?2300:1750);
}
function commit(before,title,detail,kind='action',visual=null){let snapshot=clone(before);snapshot.undo=null;state.undo=snapshot;state.history.unshift({at:new Date().toISOString(),round:state.round,actor:state.phase,title,detail,kind});state.history=state.history.slice(0,150);persist();render();message(`${title}\n${detail}`);if(visual)effect(visual.kind,visual.level);else if(['crit','summon','flame'].includes(kind))effect(kind);else if(/Dragon · Souffle|Souffle du dragon/i.test(title))effect('breath');else if(/Dragon · Déchirement/.test(title))effect('dragon');else if(/froid|givre|grêle|glace/i.test(title+' '+detail))effect('cold');else if(/métamagie|sorcellerie/i.test(title))effect('meta')}
function transaction(title,fn){const before=clone(state),result=fn();if(result===false)return false;commit(before,title,typeof result==='string'?result:'');return true}
function requireCost(cost){if(state.phase==='dragon'&&cost!=='reaction'){message('Terminez d’abord le tour du dragon.');return false}if(state.eco[cost]){message(`${cost==='bonus'?'Action bonus':cost==='reaction'?'Réaction':'Action'} déjà utilisée.`);return false}return true}
function spendPoints(cost){let feat=Math.min(cost,state.featSp);if(state.sp<cost-feat)return false;state.featSp-=feat;state.sp-=cost-feat;return true}
function canPoints(cost){return state.sp+state.featSp>=cost}
function getSpell(id){return SPELLS.find(s=>s.id===id)||STAFF_SPELLS[id]}
let pendingHitDecision=null;
function choose(title,body,buttons,variant=''){return new Promise(resolve=>{
 const dlg=$('#resolution');dlg.classList.toggle('hit-confirm',variant==='hit');$('#resolutionTitle').textContent=title;$('#resolutionBody').innerHTML=body;$('#resolutionActions').replaceChildren();$('#resolutionActions').className='dialog-actions';
 function finish(choice){let data={};$$('#resolutionBody input,#resolutionBody select,#resolutionBody textarea').forEach(e=>data[e.name]=e.value);pendingHitDecision=null;dlg.close();resolve({choice,data});if(variant==='hit')window.CompanionAPI?.sync()}
 for(const b of buttons){let btn=document.createElement('button');btn.type='button';btn.textContent=b.label;btn.className=b.value===null?'cancel':variant==='hit'?`hit-${b.value}`:'';btn.onclick=()=>finish(b.value);$('#resolutionActions').append(btn)}
 dlg.oncancel=e=>{e.preventDefault();finish(null)};dlg.showModal();if(variant==='hit'){pendingHitDecision=hit=>{const choice=hit?'yes':'no';if(!buttons.some(b=>b.value===choice))throw Error('Décision impossible pour ce jet naturel');finish(choice)};window.CompanionAPI?.sync();dlg.querySelector('.hit-yes')?.focus()}
})}
function confirmHit(title,attack){
 const buttons=attack.nat===1?[{label:'Confirmer le raté · 1 naturel',value:'no'},{label:'Annuler',value:null}]:attack.nat===20?[{label:'Confirmer le critique · 20 naturel',value:'yes'},{label:'Annuler',value:null}]:[{label:'Raté',value:'no'},{label:'Touché',value:'yes'},{label:'Annuler',value:null}];
 return choose(title,`<div class="hit-roll">${attack.nat+10}</div><div class="hit-detail">${esc(attack.display)} + bonus 10</div><p class="hit-question">Est-ce que cette attaque touche la cible ?</p>`,buttons,'hit').then(result=>{const choice=result.choice==='yes'?'hit':result.choice==='no'?'miss':null;window.__lastAttackHit=choice===null?null:choice==='hit';return {...result,choice}})
}
async function askNumber(label,def=1,min=0,max=999){let x=await choose(label,`<label>${esc(label)} <input name="amount" type="number" min="${min}" max="${max}" value="${def}"></label>`,[{label:'Valider',value:'ok'},{label:'Annuler',value:null}]);if(x.choice===null)return null;let n=Number(x.data.amount);if(!Number.isFinite(n)||n<min||n>max){message('Valeur invalide.');return null}return Math.floor(n)}
async function askText(title,fields,existing={}){let body=fields.map(f=>`<label>${esc(f.label)} ${f.type==='textarea'?`<textarea name="${f.key}" rows="4">${esc(existing[f.key]||'')}</textarea>`:`<input name="${f.key}" type="${f.type||'text'}" value="${esc(existing[f.key]??'')}" maxlength="${f.max||5000}">`}</label>`).join('');let r=await choose(title,body,[{label:'Enregistrer',value:'save'},{label:'Annuler',value:null}]);return r.choice?r.data:null}
function attackRoll(){let manual=Number($('#manual').value),mode=state.rollMode||'normal';if($('#manual').value!==''&&Number.isInteger(manual)&&manual>=1&&manual<=20){$('#manual').value='';return{nat:manual,display:`d20 manuel ${manual}`}}let a=roll(20),b=mode==='normal'?null:roll(20);return{nat:b===null?a:mode==='adv'?Math.max(a,b):Math.min(a,b),display:b===null?`d20 ${a}`:`d20 ${a} / ${b} (${mode==='adv'?'avantage':'désavantage'})`}}
function usableSpell(s,level,meta,free){let cost=s.kind==='reaction'?'reaction':meta==='quick'?'bonus':'action';if(!requireCost(cost))return false;if(s.kind==='reaction'&&meta!=='none'){message('Métamagie indisponible sur cette réaction.');return false}if(meta==='quick'&&s.kind==='reaction'){message('Une réaction ne peut pas être accélérée.');return false}if(cost==='action'&&state.bonusSpell&&s.lv>0&&state.bonusSpell!=='house-l1'){message('Après un sort en action bonus, seul un tour de magie à 1 action est autorisé, sauf règle maison Accéléré N1.');return false}if(cost==='bonus'&&state.leveledAction&&!(meta==='quick'&&s.lv===1)){message('Un sort de niveau a déjà été lancé avec l’action ce tour. La règle maison n’autorise ici que Sort accéléré sur un sort N1.');return false}if(!free&&s.lv&&state.slots[level]<=0){message(`Plus d’emplacements de niveau ${level}.`);return false}let points=meta==='quick'?2:meta==='twin'?(level||1):meta==='heighten'?3:meta==='empower'?1:0;if(meta==='empower'&&!['attack','save','storm','automatic'].includes(s.kind)){message('Sort renforcé nécessite des dés de dégâts.');return false}if(meta==='twin'&&!s.twin||meta==='heighten'&&!(s.kind==='save'||s.kind==='storm'||s.id==='radiance')){message('Cette métamagie ne s’applique pas à ce sort.');return false}if(meta==='heighten'&&!state.intensified){message('Sort intensifié non validé dans la configuration.');return false}if(!canPoints(points)){message('Points de sorcellerie insuffisants.');return false}return{cost,points}}
function spellDice(s,level){if(s.id==='orb')return[3+level-1,8];if(s.id==='vortex')return[8+level-3,6];if(s.id==='cone')return[8+level-5,8];return s.dice||[0,0]}
function applyCast(s,level,meta,free,guard){if(!free&&level)state.slots[level]--;if(free)state.cureFree=0;spendPoints(guard.points);state.eco[guard.cost]=true;if(guard.cost==='bonus')state.bonusSpell=(meta==='quick'&&s.lv===1)?'house-l1':true;else if(guard.cost==='action'&&s.lv>0)state.leveledAction=true;state.meta='none';if(s.concentration){if(state.dragon){state.dragon=null;state.sharedResistance=''}state.concentration=s.name}}
async function cast(id){let s=getSpell(id);if(!s)return;let draft=readCastDraft(s);if(draft.useStaff&&STAFF_SPELLS[id]){await useStaffSpell(id);return}let meta=state.meta,free=s.id==='cure'&&draft.free&&!!state.cureFree,level=free?1:Number(draft.level)||s.lv;
 if(s.lv&&!free&&(!Number.isInteger(level)||level<s.lv||level>5||!state.slots[level])){message('Choisissez un emplacement disponible dans la préparation du sort.');return}
 let guard=usableSpell(s,level,meta,free);if(!guard)return;
 let detail='',pendingDamage=0,critical=false,attackResults=[];
 if(s.kind==='attack'){
   let hits=meta==='twin'?2:1;
   for(let i=0;i<hits;i++){let ar=attackRoll(),nat=ar.nat,r=await confirmHit(`${s.name} · cible ${i+1}`,ar);if(!r.choice)return;attackResults.push({nat,hit:r.choice==='hit'});}
 }
 let orbCold=true;if(s.id==='orb'){let element=draft.element;if(!['froid','acide','feu','foudre','poison','tonnerre'].includes(element)){message('Choisissez un type de dégâts.');return}orbCold=element==='froid';s={...s,cold:orbCold,element}}
 let fail=0,success=0;
 if(['save','storm'].includes(s.kind)){fail=Number(draft.fail);success=Number(draft.success);if(!Number.isInteger(fail)||!Number.isInteger(success)||fail<0||success<0||fail+success>50||(meta==='twin'&&fail+success>2)){message('Nombre de cibles invalide.');return}}
 let summonResistance='';if(s.kind==='summon'){summonResistance=draft.resistance;if(!['froid','acide','feu','foudre','poison'].includes(summonResistance)){message('Choisissez la résistance partagée.');return}}
 const before=clone(state);applyCast(s,level,meta,free,guard);if(s.kind==='summon')state.sharedResistance=summonResistance;
 if(s.kind==='attack'){let pieces=[];for(let [i,r]of attackResults.entries()){if(!r.hit){pieces.push(`Cible ${i+1} : ${r.nat}+10=${r.nat+10} · raté${r.nat===1?' (1 naturel)':''}`);continue}let[n,faces]=spellDice(s,level),d=damageDice(n*(r.nat===20?2:1),faces,!!s.cold,meta==='empower'),bonus=s.cold?3:0;let extra=state.flameArmed&&level>0?damageDice(level,10):null;if(extra){state.flameArmed=false;state.flame=0}let amount=d.total+bonus+(extra?.total||0);pendingDamage+=amount;critical ||=r.nat===20;pieces.push(`Cible ${i+1} : ${r.nat}+10=${r.nat+10}${r.nat===20?' · CRITIQUE':''}\n${amount} dégâts (${d.total}${s.cold?' froid':s.element?' '+s.element:''}${bonus?' + 3 affinité':''}${extra?' + '+extra.total+' radiant':''}) · dés ${d.detail}`)}detail=pieces.join('\n');}
 else if(s.kind==='save'||s.kind==='storm'){let d,parts;if(s.kind==='storm'){let a=damageDice(2+level-4,8,false,false),b=damageDice(4,6,true,false);d={total:a.total+b.total+3,detail:`${a.detail} contondant + ${b.detail} froid +3 affinité`};parts=`${a.total} contondant + ${b.total+3} froid`}else{let[n,faces]=spellDice(s,level);d=damageDice(n,faces,!!s.cold,meta==='empower');d.total+=s.cold?3:0;parts=`${d.total} ${s.cold?'froid':'dégâts'}`}let extra=state.flameArmed&&level>0&&fail+success>0?damageDice(level,10):null;if(extra){state.flameArmed=false;state.flame=0}let full=d.total+(extra?.total||0),half=s.half?Math.floor(full/2):0;pendingDamage=fail*full+success*half;detail=`${s.save} DD18 · ${fail} échec(s), ${success} réussite(s)\n${pendingDamage} dégâts cumulés (${parts}${extra?' + '+extra.total+' radiant':''}) · ${full} par échec, ${half} par réussite. Dés : ${d.detail}${meta==='heighten'?' · premier JDS avec désavantage':''}`}
 else if(s.kind==='automatic'){let count=3+level-1,d=damageDice(count,4),extra=state.flameArmed?damageDice(level,10):null;if(extra){state.flameArmed=false;state.flame=0}pendingDamage=d.total+count+(extra?.total||0);detail=`${count} projectiles · ${d.total+count} force (${d.detail} + ${count})${extra?` + ${extra.total} radiant · Flammes pures (${extra.detail})`:''} · ${pendingDamage} dégâts cumulés · répartition libre, toucher automatique.`}
 else if(s.kind==='heal'){let d=damageDice(level,8);detail=`${d.total+3} PV rendus (dés ${d.detail} +3). ${free?'Usage gratuit consommé.':'Emplacement niveau '+level+'.'}${meta==='twin'?' Deux cibles distinctes.':''}`}
 else if(s.kind==='summon'){state.dragon={hp:50,max:50,ac:19,level:5};state.dragonEco={action:false,move:false,rends:0,breath:false};detail=`Dragon d’argent invoqué · 50 PV · CA19 · résistance partagée : ${state.sharedResistance} · joue après Samoth.`}
 else if(s.id==='counter'){let d=roll(20);detail=`Emplacement ${level} : interruption automatique des sorts de niveau ≤${level}. Si niveau supérieur : test de Charisme d20 ${d}+7=${d+7} contre DD 10 + niveau du sort adverse.`}
 else if(s.id==='shield')detail='+5 CA jusqu’au début du prochain tour ; immunité au Projectile magique.';
 else if(s.id==='absorb')detail='Résistance au type déclencheur jusqu’au début du prochain tour ; bonus à la prochaine attaque de mêlée.';
 else if(s.id==='radiance')detail='Zone maintenue. Pour chaque exposition : CON DD18, échec 4d10 radiant et 1 épuisement. Concentrez-vous.';
 else detail=`${s.desc}${s.concentration?' · Concentration active.':''}`;
 state.turnDamage+=pendingDamage;commit(before,s.name,detail+(meta!=='none'?`\nMétamagie : ${meta} (${guard.points} point(s)).`:''),critical?'crit':s.kind==='summon'?'summon':'spell',{kind:s.kind==='summon'?'summon':critical?'crit':s.cold||s.id==='storm'?s.id:s.id==='orb'&&orbCold?'vortex':s.id==='missile'?'meta':s.id==='cure'?'heal':'meta',level});
}
async function dragonAction(type){if(type==='damage'||type==='heal'){if(!state.dragon){message('Dragon absent.');return}let n=await askNumber(type==='damage'?'Dégâts au dragon':'Soins du dragon',1,0,999);if(n===null)return;transaction(type==='damage'?'Dragon blessé':'Dragon soigné',()=>{let d=state.dragon,old=d.hp;d.hp=Math.min(d.max,Math.max(0,d.hp+(type==='heal'?n:-n)));let line=`${old} → ${d.hp}/${d.max} PV.`;if(!d.hp){state.dragon=null;state.sharedResistance='';state.concentration='';line+=' Invocation terminée.';if(state.phase==='dragon')state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return line});return}
 if(type==='dismiss'){if(!state.dragon)return;transaction('Dragon renvoyé',()=>{state.dragon=null;state.concentration='';state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return 'Concentration terminée.'});return}
 if(!state.dragon||state.phase!=='dragon'){message('Le dragon joue immédiatement après Samoth : terminez d’abord le tour de Samoth.');return}
 if(type==='dodge'){if(state.dragonEco.action){message('Action du dragon déjà utilisée.');return}transaction('Dragon · Esquive',()=>{state.dragonEco.action=true;return 'Les attaques contre le dragon ont désavantage jusqu’à son prochain tour.'});return}
 if(type==='rend'){if(state.dragonEco.rends>=2||state.dragonEco.action){message('Deux Déchirements maximum pendant son action multiple.');return}let ar=attackRoll(),r=await confirmHit('Déchirement du dragon',ar);if(!r.choice)return;transaction('Dragon · Déchirement',()=>{state.dragonEco.rends++;let hit=r.choice==='hit',d=hit?damageDice(ar.nat===20?2:1,6):null,amount=hit?d.total+9:0;state.dragonDamage+=amount;return `${ar.nat}+10=${ar.nat+10} · ${hit?`${amount} perforants (${d.detail}+9)`:'raté'} · ${state.dragonEco.rends}/2 attaques.`});return}
 if(type==='breath'){if(state.dragonEco.breath||state.dragonEco.action){message('Souffle déjà utilisé.');return}let r=await choose('Souffle du dragon',`<label>Type <select name="type">${['froid','acide','feu','foudre','poison'].map(t=>`<option>${t}</option>`).join('')}</select></label><div class="field-row"><label>Échecs <input name="fail" type="number" min="0" value="1"></label><label>Réussites <input name="success" type="number" min="0" value="0"></label></div>`,[{label:'Résoudre',value:'go'},{label:'Annuler',value:null}]);if(!r.choice)return;let f=Number(r.data.fail),s=Number(r.data.success);if(!Number.isInteger(f)||!Number.isInteger(s)||f<0||s<0||f+s>50){message('Nombre de cibles invalide.');return}transaction('Dragon · Souffle',()=>{let d=damageDice(2,6),amount=f*d.total+s*Math.floor(d.total/2);state.dragonEco.breath=true;state.dragonDamage+=amount;return `DEX DD18 · ${d.total} ${r.data.type} (${d.detail}) par échec, moitié en réussite · ${amount} dégâts cumulés.`})}
}
function stopConcentration(){if(!state.concentration)return;transaction('Concentration terminée',()=>{let prev=state.concentration;state.concentration='';state.dragon=null;state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}return prev+' terminé ; invocation éventuelle disparue.'})}
async function useAbility(id){if(id==='restShort'||id==='restLong'){rest(id==='restLong');return}if(id==='radianceTick'){if(state.concentration!=='Rayonnement écœurant'){message('Rayonnement écœurant doit être maintenu.');return}let r=await choose('Exposition au rayonnement',`<div class="field-row"><label>Échecs <input name="fail" type="number" min="0" value="1"></label><label>Réussites <input name="success" type="number" min="0" value="0"></label></div>`,[{label:'Résoudre',value:'go'},{label:'Annuler',value:null}]);if(!r.choice)return;let f=Number(r.data.fail),s=Number(r.data.success);if(!Number.isInteger(f)||!Number.isInteger(s)||f<0||s<0||f+s>50){message('Nombre de cibles invalide.');return}transaction('Exposition au rayonnement',()=>{let d=damageDice(4,10),total=f*d.total;state.turnDamage+=total;return `CON DD18 · ${f} échec(s), ${s} réussite(s) · ${total} radiants (${d.detail}, ${d.total} par échec) et 1 épuisement par cible en échec. Aucun emplacement dépensé.`});return}if(id==='endConcentration'){stopConcentration();return}if(id==='flame'){transaction('Flammes de magie pure',()=>{if(!state.flame&&!state.flameArmed){message('Pouvoir déjà consommé aujourd’hui.');return false}state.flameArmed=!state.flameArmed;return state.flameArmed?'Prêt pour le prochain sort de niveau 1 ou plus qui inflige des dégâts.':'Déclenchement annulé.'});return}
 if(id==='wings'){if(!requireCost('reaction')||!state.wings){message('Réaction utilisée ou ailes épuisées.');return}transaction('Ailes protectrices',()=>{state.eco.reaction=true;state.wings--;return `+4 CA à Samoth ou un allié à 1,5 m contre une attaque ; ${state.wings}/4 usages restants.`});return}
 if(id==='slotToPoints'||id==='pointsToSlot'){if(!requireCost('bonus'))return;let level=Number($('#convertLevel').value);if(id==='slotToPoints'&&(!state.slots[level]||state.sp+level>10)){message('Emplacement absent ou capacité de 10 points de sorcellerie dépassée.');return}if(id==='pointsToSlot'&&(state.sp<SP_COST[level]||state.slots[level]>=MAX[level])){message('Points insuffisants ou maximum d’emplacements atteint.');return}transaction('Incantation flexible',()=>{state.eco.bonus=true;if(id==='slotToPoints'){state.slots[level]--;state.sp+=level;return `Emplacement N${level} converti en ${level} point(s).`}state.sp-=SP_COST[level];state.slots[level]++;return `${SP_COST[level]} points convertis en emplacement N${level}.`});return}
 if(id==='vial'){if(!state.vial||state.hitDice===10){message('La fiole exige des dés de vie dépensés, une fois par jour.');return}transaction('Fiole sanguine',()=>{state.vial=0;let amount=Math.min(5,10-state.sp);state.sp+=amount;return `+${amount} point(s) de sorcellerie, ${state.sp}/10.`});return}
 if(id==='resist'){if(state.sp<1){message('Il faut 1 point de sorcellerie ordinaire.');return}transaction('Affinité élémentaire',()=>{state.sp--;return 'Résistance au froid pendant 1 heure (1 SP consommé).'});return}
 if(id==='staffDawn'){transaction('Aube · bâton',()=>{let d=roll(4)+2,old=state.staff;state.staff=Math.min(8,state.staff+d);return `${old} → ${state.staff}/8 charges (récupération 1d4+2 = ${d}).`});return}
 if(id==='hitDice'){let n=await askNumber('Dés de vie à dépenser',1,1,state.hitDice);if(n===null)return;transaction('Dés de vie',()=>{let results=Array.from({length:n},()=>roll(6)+2),heal=results.reduce((a,b)=>a+b,0),old=state.hp;state.hp=Math.min(72,state.hp+heal);state.hitDice-=n;let vial='';if(state.vial&&state.sp<10){let gain=Math.min(5,10-state.sp);state.sp+=gain;state.vial=0;vial=` · Fiole sanguine : +${gain} SP (usage du jour consommé)`}return `${n}d6+${n*2} → ${heal} PV (${old} → ${state.hp}/72)${vial}.`});return}
 if(id==='feat'){transaction('Configuration · Adepte de métamagie',()=>{state.featEnabled=!state.featEnabled;state.featSp=state.featEnabled?2:0;return state.featEnabled?'Don activé : 2 points réservés à la métamagie.':'Don désactivé.'});return}
 if(id==='intensified'){transaction('Configuration · Sort intensifié',()=>{state.intensified=!state.intensified;if(!state.intensified&&state.meta==='heighten')state.meta='none';return state.intensified?'Option autorisée par le MJ.':'Option désactivée.'});return}}
function nextTurn(){transaction('Tour suivant',()=>{if(state.phase==='samoth'&&state.dragon){state.phase='dragon';state.dragonEco={action:false,move:false,rends:0,breath:false};state.dragonDamage=0;return 'Tour du dragon immédiatement après Samoth.'}let dodge=state.phase==='dragon'&&state.dragon&&!state.dragonEco.rends&&!state.dragonEco.breath&&!state.dragonEco.action;state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.turnDamage=0;state.bonusSpell=false;state.leveledAction=false;return `${dodge?'Le dragon sans ordre a esquivé. ':''}Round ${state.round} · économie de Samoth restaurée ; concentration maintenue.`});if(state.phase==='dragon')view('dragon');else view('combat')}
function rest(long){if(!confirm(`Effectuer un repos ${long?'long':'court'} ?`))return;transaction(long?'Repos long':'Repos court',()=>{if(!long)return 'Les emplacements et points de sorcellerie ne reviennent pas. Dépensez les dés de vie avec le bouton Ressources ; la fiole s’active automatiquement.';let old=state.hp;state.hp=72;state.tempHp=0;state.slots={...MAX};state.sp=10;state.featSp=state.featEnabled?2:0;state.hitDice=Math.min(10,state.hitDice+5);state.cureFree=1;state.wings=4;state.flame=1;state.flameArmed=false;state.vial=1;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false;state.concentration='';state.dragon=null;state.sharedResistance='';state.phase='samoth';return `PV ${old} → 72, emplacements et sorcellerie restaurés, +5 dés de vie maximum, usages journaliers remis. Bâton : récupération à l’aube séparée.`})}
function applyIncomingHp(n,kind){transaction(kind==='damage'?'Dégâts reçus':'Soins reçus',()=>{let old=state.hp,t=state.tempHp;if(kind==='damage'){let absorbed=Math.min(t,n);state.tempHp-=absorbed;state.hp=Math.max(0,state.hp-(n-absorbed))}else state.hp=Math.min(72,state.hp+n);let check='';if(kind==='damage'&&state.concentration&&n>0){let dc=Math.max(10,Math.floor(n/2)),natural=roll(20),total=natural+6;check=` · Concentration CON ${natural}+6=${total} contre DD${dc}`;if(total<dc){check+=' : perdue';state.concentration='';state.dragon=null;state.sharedResistance='';if(state.phase==='dragon'){state.phase='samoth';state.round++;state.eco={action:false,bonus:false,reaction:false,move:false};state.bonusSpell=false;state.leveledAction=false}}else check+=' : maintenue'}return `${n} ${kind==='damage'?'dégâts':'PV de soins'} · PV ${old}→${state.hp}/72, temporaires ${t}→${state.tempHp}${check}.`});}
let spellFilter='all';
function showPowerTab(tab){$$('[data-power-pane]').forEach(e=>e.classList.toggle('active',e.dataset.powerPane===tab));$$('[data-power-tab]').forEach(e=>{let active=e.dataset.powerTab===tab;e.classList.toggle('active',active);e.setAttribute('aria-pressed',String(active))})}
const mobileGroups={combat:['combat','dragon'],powers:['powers'],social:['social','inventory'],history:['history','rules']};
function updateMobileNavigation(id){let group=Object.keys(mobileGroups).find(key=>mobileGroups[key].includes(id))||'combat';$$('[data-mobile-view]').forEach(b=>{let active=b.dataset.mobileView===group;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});let labels={combat:'Samoth',dragon:'Dragon',social:'Profil',inventory:'Inventaire',history:'Journal / Notes',rules:'Règles'};$('#mobileSubnav').innerHTML=mobileGroups[group].length>1?mobileGroups[group].map(key=>`<button data-sub-view="${key}" class="${key===id?'active':''}" aria-current="${key===id?'page':'false'}">${labels[key]}</button>`).join(''):'';}
const desktopGroups={combat:[['combat','Attaques'],['dragon','Dragon']],powers:[['powers','Sorts & pouvoirs']],social:[['social','Profil'],['inventory','Inventaire']],history:[['history','Journal / Notes'],['rules','Référence']]};
const desktopNav=document.createElement('nav');desktopNav.className='samoth-desktop-nav';desktopNav.setAttribute('aria-label','Navigation principale');
const desktopSubnav=document.createElement('nav');desktopSubnav.className='samoth-desktop-subnav';desktopSubnav.setAttribute('aria-label','Sous-sections');
desktopNav.innerHTML='<button data-desktop-group="combat">Combat</button><button data-desktop-group="powers">Sorts & pouvoirs</button><button data-desktop-group="social">Social</button><button data-desktop-group="history">Journal</button>';
document.querySelector('.nav')?.after(desktopNav,desktopSubnav);
desktopNav.onclick=e=>{const key=e.target.closest('[data-desktop-group]')?.dataset.desktopGroup;if(key)view(desktopGroups[key][0][0])};
desktopSubnav.onclick=e=>{const key=e.target.closest('[data-desktop-view]')?.dataset.desktopView;if(key)view(key)};
function updateDesktopNavigation(id){const group=Object.keys(desktopGroups).find(key=>desktopGroups[key].some(([view])=>view===id))||'combat';desktopNav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.desktopGroup===group));desktopSubnav.innerHTML=desktopGroups[group].map(([key,label])=>`<button data-desktop-view="${key}" class="${key===id?'active':''}">${label}</button>`).join('')}
function view(id){$$('.view').forEach(e=>e.classList.toggle('active',e.id===id));$$('.nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===id));updateMobileNavigation(id);updateDesktopNavigation(id);window.scrollTo({top:0,behavior:'instant'})}
function selectedSpell(){return getSpell(state.selectedSpell)||SPELLS[0]}
function metaFits(s,meta){return meta==='none'||meta==='quick'&&s.kind!=='reaction'||meta==='twin'&&!!s.twin||meta==='empower'&&['attack','save','storm','automatic'].includes(s.kind)||meta==='heighten'&&state.intensified&&(['save','storm'].includes(s.kind)||s.id==='radiance')}
function spellBlocked(s){if(state.phase==='dragon')return 'Tour du dragon en cours';let meta=state.meta;if(!metaFits(s,meta))return 'Métamagie incompatible avec ce sort';let points=meta==='quick'?2:meta==='twin'?(s.lv||1):meta==='heighten'?3:meta==='empower'?1:0;if(!canPoints(points))return 'Points de sorcellerie insuffisants';let cost=s.kind==='reaction'?'reaction':meta==='quick'?'bonus':'action';if(state.eco[cost])return `${cost==='bonus'?'Action bonus':cost==='reaction'?'Réaction':'Action'} déjà utilisée`;if(cost==='action'&&state.bonusSpell&&s.lv>0&&state.bonusSpell!=='house-l1')return 'Seul un tour de magie à 1 action est possible';if(cost==='bonus'&&state.leveledAction&&!(meta==='quick'&&s.lv===1))return 'Sort de niveau déjà lancé avec l’action';if(s.lv&&!(s.id==='cure'&&state.cureFree)&&!Object.keys(MAX).some(n=>Number(n)>=s.lv&&state.slots[n]>0))return 'Aucun emplacement compatible';return ''}
function renderCastSetup(s){let d=draftFor(s),fields=[],staff=STAFF_SPELLS[s.id],staffOnly=STAFF_ONLY.has(s.id);
 if(staff){if(staffOnly)d.useStaff=true;fields.push(`<label class="staff-source-toggle ${staffOnly?'locked':''}"><span><input type="checkbox" data-cast-field="useStaff" ${d.useStaff?'checked':''} ${staffOnly?'disabled':''}> <b>Bâton</b></span><strong>${state.staff}/8 · coût ${staff.cost}</strong></label>`)}
 if(s.lv&&!staffOnly){let opts=Object.keys(MAX).map(Number).filter(n=>n>=s.lv&&state.slots[n]>0),free=s.id==='cure'&&state.cureFree;let choices=[...(free?['<option value="free">Gratuit</option>']:[]),...opts.map(n=>`<option value="${n}">N${n} · ${state.slots[n]} restant(s)</option>`)];let value=free&&d.free?'free':opts.includes(Number(d.level))?String(d.level):free?'free':String(opts[0]||'');d.free=value==='free';d.level=d.free?1:Number(value);fields.push(`<label class="cast-choice compact-field">Emplacement<select data-cast-field="${free?'free':'level'}" id="castLevel" ${d.useStaff?'disabled':''}>${choices.join('')}</select></label>`)}
 if(s.id==='orb')fields.push(`<label class="cast-choice compact-field">Dégâts<select data-cast-field="element">${['froid','acide','feu','foudre','poison','tonnerre'].map(t=>`<option ${d.element===t?'selected':''}>${t}</option>`).join('')}</select></label>`);
 if(['save','storm'].includes(s.kind)){fields.push(`<label class="compact-field">Échecs JdS<input data-cast-field="fail" type="number" min="0" max="50" inputmode="numeric" value="${Number.isInteger(d.fail)?d.fail:1}"></label>`,`<label class="compact-field">Réussites JdS<input data-cast-field="success" type="number" min="0" max="50" inputmode="numeric" value="${Number.isInteger(d.success)?d.success:0}"></label>`)}
 if(s.kind==='summon')fields.push(`<label class="cast-choice compact-field">Résistance<select data-cast-field="resistance">${['froid','acide','feu','foudre','poison'].map(t=>`<option ${d.resistance===t?'selected':''}>${t}</option>`).join('')}</select></label>`);
 $('#castSetup').innerHTML=fields.length?`<div class="cast-fields compact-cast-fields">${fields.join('')}</div>`:'';
 $('#castSetup').hidden=!fields.length;
 let level=$('#castLevel');if(level)level.value=d.free?'free':String(d.level);
}
function renderCombatSelector(){let selected=selectedSpell();state.selectedSpell=selected.id;let select=$('#combatSpell');
 const normal=[...new Set(SPELLS.filter(s=>!STAFF_ONLY.has(s.id)).map(s=>s.lv))].map(lv=>`<optgroup label="${lv?'Niveau '+lv+' · '+state.slots[lv]+'/'+MAX[lv]+' emplacements':'Tours de magie · illimités'}">${SPELLS.filter(s=>s.lv===lv&&!STAFF_ONLY.has(s.id)).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</optgroup>`).join('');
 const staffOnly=['hands','fog','storm','cone','wall'].map(id=>STAFF_SPELLS[id]).filter(Boolean);
 const staffGroup=`<optgroup label="Bâton de confluence · ${state.staff}/8 charges">${staffOnly.map(s=>`<option value="${s.id}">${esc(s.name)} · ${s.cost} charge${s.cost>1?'s':''}</option>`).join('')}</optgroup>`;
 select.innerHTML=normal+staffGroup;select.value=selected.id;
 let role=spellRole(selected),draft=draftFor(selected),staff=STAFF_SPELLS[selected.id],usingStaff=!!(staff&&draft.useStaff),blocked=usingStaff?(state.phase==='dragon'?'Tour du dragon en cours':state.eco.action?'Action déjà utilisée':state.staff<staff.cost?'Charges du bâton insuffisantes':''):spellBlocked(selected),cost=selected.kind==='reaction'?'Réaction':usingStaff?'Action':state.meta==='quick'?'Action bonus':'Action',chosenLevel=selected.lv&&draft.level>=selected.lv&&state.slots[draft.level]?draft.level:selected.lv,slots=usingStaff?`Bâton · ${state.staff}/8 charges · coût ${staff.cost}`:selected.lv?selected.id==='cure'&&state.cureFree&&draft.free?'usage gratuit disponible':`N${chosenLevel} · ${state.slots[chosenLevel]??0}/${MAX[chosenLevel]??0} disponibles`:'Tour de magie · illimité';$('#combat').dataset.spellRole=role;$('#casterResource').textContent=slots;$('#combatPreview').innerHTML=`<div class="caster-preview role-${role}"><div><span class="spell-role">${ROLE_LABEL[role]}</span><h3>${esc(selected.name)}</h3><p>${esc(selected.desc||staff?.desc||'')}</p></div><div class="caster-facts"><span>${cost}</span><span>${esc(selected.range||'Bâton')}</span>${selected.concentration?'<span>Concentration</span>':''}</div></div>`;renderCastSetup(selected);$('#combatCast').dataset.cast=selected.id;$('#combatCast').textContent=`Lancer ${selected.name}`;$('#combatCast').disabled=!!blocked;$('#combatBlocked').textContent=blocked;$('#attackControls').hidden=selected.kind!=='attack';let flame=$('#flameQuick');flame.classList.toggle('armed',!!state.flameArmed);flame.disabled=!state.flame&&!state.flameArmed;flame.querySelector('b').textContent=state.flameArmed?'Flammes pures armées':state.flame?'Armer Flammes pures':'Flammes pures utilisées';flame.querySelector('small').textContent=state.flameArmed?'Prochain sort de niveau infligeant des dégâts · toucher pour désarmer':state.flame?'1 usage · +1d10 radiant par niveau du sort':'Rechargement au repos long';}
function renderStaffCombat(){const box=$('#staffCombat');if(!box)return;const actionBusy=state.phase==='dragon'||state.eco.action;const order=['hands','fog','vortex','storm','cone','wall'];box.innerHTML=`<div class="staff-combat-head"><div><div class="eyebrow">Bâton de confluence · source magique</div><h2>Bâton de Samoth</h2><p>Les sorts ci-dessous consomment des charges, pas d’emplacement. Vortex reste également disponible depuis le grimoire avec un emplacement.</p></div><div class="staff-charge-orb"><b>${state.staff}</b><small>/ 8 charges</small></div></div><div class="staff-pips">${Array.from({length:8},(_,i)=>`<span class="${i<state.staff?'on':''}"></span>`).join('')}</div><div class="staff-spells">${order.map(id=>{let s=STAFF_SPELLS[id],disabled=actionBusy||state.staff<s.cost;return `<button class="staff-spell staff-${id}" data-staff-spell="${id}" ${disabled?'disabled':''}><span><b>${s.name}</b><small>${s.desc}</small></span><strong>${s.cost} charge${s.cost>1?'s':''}</strong></button>`}).join('')}</div>`;}
async function useStaffSpell(id){const s=STAFF_SPELLS[id];if(!s)return;if(!requireCost('action'))return;if(state.staff<s.cost){message('Charges insuffisantes pour '+s.name+'.');return}let fail=0,success=0;if(s.kind==='save'||s.kind==='storm'){let r=await choose(s.name,`<p class="jds-help"><b>Combien de créatures sont dans la zone ?</b><br>Échec = nombre de créatures qui ratent leur JdS DD18 ; Réussite = nombre qui réussissent.</p><div class="field-row"><label>Échecs au JdS <input name="fail" type="number" min="0" max="50" value="1"></label><label>Réussites au JdS <input name="success" type="number" min="0" max="50" value="0"></label></div>`,[{label:'Lancer avec le bâton',value:'go'},{label:'Annuler',value:null}]);if(!r.choice)return;fail=Number(r.data.fail);success=Number(r.data.success);if(!Number.isInteger(fail)||!Number.isInteger(success)||fail<0||success<0||fail+success>50){message('Nombre de cibles invalide.');return}}
 const before=clone(state);state.staff-=s.cost;state.eco.action=true;let detail=`${s.cost} charge(s) dépensée(s) · ${state.staff}/8 restantes.`,pending=0;
 if(id==='hands'||id==='vortex'||id==='cone'){const [n,diceFaces]=s.dice,d=damageDice(n,diceFaces,true,false);let full=d.total+3,half=Math.floor(full/2);pending=fail*full+success*half;detail+=` ${s.save} DD18 · ${fail} échec(s), ${success} réussite(s) · ${pending} dégâts cumulés · ${full} par échec, ${half} par réussite (dés ${d.detail} +3 affinité).`;}
 else if(id==='storm'){let a=damageDice(2,8),b=damageDice(4,6,true),full=a.total+b.total+3,half=Math.floor(full/2);pending=fail*full+success*half;detail+=` DEX DD18 · ${fail} échec(s), ${success} réussite(s) · ${pending} dégâts cumulés · ${full} par échec, ${half} par réussite (2d8 contondant + 4d6 froid +3).`;}
 else if(id==='fog'){state.concentration='Nappe de brouillard';detail+=' Zone fortement obscurcie créée · concentration active.';}
 else if(id==='wall'){state.concentration='Mur de glace';detail+=' Mur de glace dressé · concentration active ; dégâts/sections à résoudre selon la table.';}
 state.turnDamage+=pending;commit(before,'Bâton · '+s.name,detail,'staff',{kind:id,level:s.cost});}
function render(){document.querySelectorAll('[data-rollmode]').forEach(b=>b.classList.toggle('on',b.dataset.rollmode===state.rollMode));const d=state.dragon,dragonPhase=state.phase==='dragon';$('#hp').value=state.hp;$('#tempHp').value=state.tempHp||'';$('#turn').textContent=state.round;$('#round').textContent=state.round;$('#actor').textContent=dragonPhase?'Dragon':'Samoth';$('#damageTurn').textContent=dragonPhase?state.dragonDamage:state.turnDamage;$('#damageActor').textContent=dragonPhase?'par le dragon':'par Samoth';$('#concText').textContent=state.concentration||'Aucune';$('#concButton').classList.toggle('used',!state.concentration);$('#nextTurn').textContent=dragonPhase?'Fin du tour du dragon ›':d?'Tour du dragon ›':'Round suivant ›';$('#undo').disabled=!state.undo;renderResources();renderSpellList();
 $$('[data-econ]').forEach(b=>{let key=b.dataset.econ,used=dragonPhase?(key==='action'?state.dragonEco.action||state.dragonEco.rends>=2&&state.dragonEco.breath:key==='move'?state.dragonEco.move:key==='reaction'?state.eco.reaction:false):state.eco[key];b.classList.toggle('used',!!used);b.querySelector('small').textContent=used?'Utilisée':key==='move'?(dragonPhase?'9 / 18 m':'9 m'):'Libre';b.disabled=dragonPhase&&key==='bonus'});
 renderCombatSelector();$$('[data-cast]').forEach(b=>{let s=getSpell(b.dataset.cast);if(!s)return;let reason=spellBlocked(s)||(b.classList.contains('dragon-summon')&&d?'Dragon déjà invoqué':'');b.disabled=!!reason;b.title=reason});
 $$('[data-ability="wings"]').forEach(b=>b.disabled=dragonPhase||state.eco.reaction||!state.wings);
 $$('[data-ability="radianceTick"]').forEach(b=>b.disabled=state.concentration!=='Rayonnement écœurant');
 $('#dragonStatus').textContent=d?`· ${d.hp}/${d.max} PV`:'· non invoqué';$('#dragonResistance').textContent=d?`Résistance partagée : ${state.sharedResistance}.`:'La convocation exige un emplacement N5 et la concentration.';$('#dragonTurnState').textContent=d?`${dragonPhase?'À jouer maintenant':'Attend son tour'} · Déchirements ${state.dragonEco.rends}/2 · Souffle ${state.dragonEco.breath?'utilisé':'libre'} · ${state.dragonDamage} dégâts ce tour.`:'Invoquez-le depuis Combat ou Sorts.';
 $$('[data-dragon="rend"],[data-dragon="breath"],[data-dragon="dodge"]').forEach(b=>b.disabled=!d||!dragonPhase||state.dragonEco.action||(b.dataset.dragon==='rend'&&state.dragonEco.rends>=2)||(b.dataset.dragon==='breath'&&state.dragonEco.breath)||(b.dataset.dragon==='dodge'&&(state.dragonEco.rends>0||state.dragonEco.breath)));
 renderInventory();renderHistory();}
function renderResources(){$('#resourcesBody').innerHTML=`<div class="resource-line"><span>Points de sorcellerie</span><strong>${state.sp}/10</strong></div><div class="resource-line"><span>Adepte de métamagie (option)</span><button class="ability" data-ability="feat">${state.featEnabled?'Activé · '+state.featSp+'/2':'Désactivé'}</button></div><div class="resource-line"><span>Dés de vie d6</span><strong>${state.hitDice}/10</strong><button class="ability" data-ability="hitDice">Dépenser</button></div>`;
 const options=[['none','Aucune','Sort normal',0],['quick','Accéléré','Action → bonus',2],['twin','Jumeau','Deux cibles · coût du niveau',1],['empower','Renforcé','Relance 3 dés faibles',1],...(state.intensified?[['heighten','Intensifié','Premier JDS désavantagé',3]]:[])];
 $('#combatSp').textContent=`${state.sp+state.featSp}/${state.featEnabled?'12':'10'} SP`;
 $('#metaBody').innerHTML=options.map(([key,label,description,cost])=>{let selected=state.meta===key,spell=selectedSpell(),points=key==='twin'?(spell.lv||1):cost,unavailable=state.phase==='dragon'||!canPoints(points)||!metaFits(spell,key),price=key==='none'?'':key==='twin'?points+(spell.lv?'+':'')+' SP':cost+' SP';return `<button class="meta-chip ${selected?'selected':''}" data-meta="${key}" aria-pressed="${selected}" aria-label="${label}${price?' · '+price:''} · ${description}" title="${unavailable&&!metaFits(spell,key)?'Non applicable à '+spell.name:description}" ${unavailable?'disabled':''}><span>${label}</span>${price?`<small>${price}</small>`:''}</button>`}).join('');
 $('#metaStatus').textContent=state.phase==='dragon'?'Tour du dragon':state.meta==='none'?'Choisir avant le sort':`${options.find(option=>option[0]===state.meta)?.[1]||'Métamagie'} · ${options.find(option=>option[0]===state.meta)?.[2]||''}`;
 $('#intensifiedToggle').textContent=state.intensified?'Autorisé':'Désactivé';
 $('#convertLevel').innerHTML=Object.keys(MAX).map(n=>`<option value="${n}">Niveau ${n} · coût ${SP_COST[n]} SP</option>`).join('');$('#chargesBody').innerHTML=`<div class="resource-line"><span>Bâton de confluence</span><strong>${state.staff}/8 charges</strong></div><div class="resource-line"><span>Sorts du bâton</span><small>Mains 1 · Brouillard 1 · Vortex 3 · Grêle 4 · Cône 5 · Mur 4</small></div><div class="resource-line">Soins gratuit <strong>${state.cureFree}/1</strong></div><div class="resource-line">Ailes protectrices <strong>${state.wings}/4</strong></div><div class="resource-line">Flammes pures <strong>${state.flame}/1</strong></div><div class="list"><button class="ability react" data-ability="wings">Ailes protectrices · réaction</button><button class="ability" data-ability="staffDawn">Aube · récupérer charges</button><button class="ability" data-ability="resist">Résistance au froid · 1 SP</button></div>`}
function renderSpellList(){
 const slots=Object.keys(MAX).map(n=>`<div class="slot-group"><b>N${n}</b><div class="dots" aria-label="Emplacements de niveau ${n}">${Array.from({length:MAX[n]},(_,i)=>`<button class="dot ${i<state.slots[n]?'on':''}" data-slot-level="${n}" data-slot-index="${i}" aria-label="Niveau ${n}, emplacement ${i+1} ${i<state.slots[n]?'disponible':'utilisé'}" title="Ajuster manuellement les emplacements"></button>`).join('')}</div><small>${state.slots[n]}/${MAX[n]}</small></div>`).join('');
 let sections=[...new Set(SPELLS.filter(s=>!STAFF_ONLY.has(s.id)).map(s=>s.lv))].map(lv=>{let visible=SPELLS.filter(s=>s.lv===lv&&!STAFF_ONLY.has(s.id)&&(spellFilter==='all'||spellRole(s)===spellFilter));if(!visible.length)return '';return `<article class="card full spell-section"><h2>${lv?'Niveau '+lv:'Tours de magie'}</h2><div class="spell-grid">${visible.map(s=>{let role=spellRole(s),source='https://www.aidedd.org/dnd/sorts.php?vf='+SPELL_SOURCE[s.id];return `<article class="spell role-${role}"><div class="eyebrow">${s.kind==='reaction'?'Réaction':'Action'} · ${ROLE_LABEL[role]}</div><h3>${esc(s.name)}</h3><div class="meta">${esc(s.range)}${s.concentration?' · concentration':''}${s.id==='cure'&&state.cureFree?' · usage gratuit disponible':''}</div><details class="spell-doc"><summary>Description du sort</summary><div class="spell-doc-body"><b>Incantation :</b> ${s.kind==='reaction'?'1 réaction':'1 action'}<br><b>Portée :</b> ${esc(s.range)}<br><b>Composantes :</b> ${esc(s.components)}<br><b>Durée :</b> ${esc(s.duration||'Instantanée')}<p>${esc(s.desc)}</p>${s.id==='vortex'?'<p><em>Adaptation maison de Boule de feu : appliquer la fiche et le grimoire de Samoth pour les valeurs exactes.</em></p>':''}<a class="spell-doc-source" href="${source}" target="_blank" rel="noopener noreferrer">${s.id==='vortex'?'Base AideDD : Boule de feu':'Fiche AideDD'} ↗</a></div></details><button class="primary" data-cast="${s.id}">Lancer${s.id==='cure'&&state.cureFree?' · gratuit disponible':''}</button>${s.id==='radiance'&&state.concentration===s.name?'<button class="ability" data-ability="radianceTick">Résoudre une exposition</button>':''}</article>`}).join('')}</div></article>`}).join('');
 const roles=['froid','defense','soutien','controle','soin','invocation','arcane'];
 const filters=`<button class="${spellFilter==='all'?'active':''}" data-spell-filter="all" aria-pressed="${spellFilter==='all'}">Tous <small>${SPELLS.length}</small></button>${roles.map(role=>{let count=SPELLS.filter(s=>spellRole(s)===role).length;return `<button class="role-${role} ${spellFilter===role?'active':''}" data-spell-filter="${role}" aria-pressed="${spellFilter===role}" ${count?'':'disabled'}>${ROLE_LABEL[role]} <small>${count}</small></button>`}).join('')}`;
 $('#spellList').innerHTML=`<article class="card full spell-slots"><div><h2>Emplacements</h2><p class="meta">Consommation automatique à l’incantation · ajustement manuel par les points · repos long</p></div><div class="slot-groups">${slots}</div></article><div class="spell-legend" role="group" aria-label="Filtrer les sorts par type">${filters}</div>${sections}`;
}
const SOCIAL={Caractéristiques:{FOR:[8,-1],DEX:[13,1],CON:[14,2],INT:[12,1],SAG:[10,0],CHA:[17,3]},'Jets de sauvegarde':{FOR:-1,DEX:1,CON:6,INT:1,SAG:0,CHA:7},Compétences:{Athlétisme:-1,Acrobaties:1,Discrétion:1,Escamotage:1,Arcanes:5,Histoire:1,Investigation:1,Nature:1,Religion:5,Dressage:0,Intuition:4,Médecine:0,Perception:0,Survie:0,Intimidation:7,Persuasion:7,Représentation:3,Tromperie:7}};
let socialPane='skills',socialMode='normal',journalPane='mechanical';
function renderSocial(){let container=$('#socialBody');if(!container)return;
 const abilities=SOCIAL.Caractéristiques,saves=SOCIAL['Jets de sauvegarde'],skills=SOCIAL.Compétences;
 const list=(values,kind)=>Object.entries(values).map(([name,val])=>{let score=Array.isArray(val)?val[0]:null,bonus=Array.isArray(val)?val[1]:val,label=(kind==='saves'?'JdS ':'')+name;return '<button type="button" class="social-roll" data-roll="'+esc(label)+'" data-bonus="'+bonus+'"><span><b>'+esc(name)+'</b>'+(score!==null?'<small>Score '+score+'</small>':'')+'</span><strong>'+(bonus>=0?'+':'')+bonus+'</strong></button>'}).join('');
 container.innerHTML='<div class="social-v3-heading"><div><h2>Social · Samoth</h2><p class="social-v3-sub">Jets de la fiche et informations utiles.</p></div></div>'+
 '<nav class="social-v3-tabs" aria-label="Profil social"><button type="button" data-social-pane="skills" class="'+(socialPane==='skills'?'active':'')+'">Compétences</button><button type="button" data-social-pane="abilities" class="'+(socialPane==='abilities'?'active':'')+'">Carac. & JdS</button><button type="button" data-social-pane="info" class="'+(socialPane==='info'?'active':'')+'">Infos utiles</button></nav>'+
 '<div class="social-v3-mode"><button type="button" data-social-mode="normal" class="'+(socialMode==='normal'?'active':'')+'">Normal</button><button type="button" data-social-mode="adv" class="'+(socialMode==='adv'?'active':'')+'">Avantage</button><button type="button" data-social-mode="dis" class="'+(socialMode==='dis'?'active':'')+'">Désavantage</button></div>'+
 (socialPane==='skills'?'<article class="social-v3-card"><h3>Compétences</h3><div class="social-v3-roll-grid">'+list(skills,'skills')+'</div></article>':socialPane==='abilities'?'<div class="social-v3-grid"><article class="social-v3-card"><h3>Caractéristiques</h3><div class="social-v3-roll-grid">'+list(abilities,'abilities')+'</div></article><article class="social-v3-card"><h3>Jets de sauvegarde</h3><div class="social-v3-roll-grid">'+list(saves,'saves')+'</div></article></div>':'<article class="social-v3-card"><h3>Informations utiles</h3><div class="social-v3-extra"><div><small>Langues</small><b>Commun, elfique, géant, orc, draconique, primordial</b></div><div><small>Vision</small><b>Vision dans le noir · 18 m</b></div><div><small>Ascendance féerique</small><b>Avantage aux JdS contre charme · immunité au sommeil magique</b></div><div><small>Passifs</small><b>Perception 10 · Intuition 14 · Investigation 11</b></div></div></article>');
}
function renderInventory(){let area=$('#itemsBody');area.innerHTML=['equipment','misc'].map(cat=>`<h3 class="section-label">${cat==='equipment'?'Équipements':'Objets divers et consommables'}</h3>${state.items.filter(i=>i.category===cat).map(i=>`<div class="item-row">${i.image&&/^(https:\/\/|data:image\/)/.test(i.image)?`<img src="${esc(i.image)}" alt="">`:'<span aria-hidden="true">❄</span>'}<div><b>${esc(i.name)}</b> ×${i.qty}${i.equipped?' · équipé':''}<p>${esc(i.note)}</p></div><button class="ability" data-item="${esc(i.id)}">Modifier</button>${i.qty>0?`<button class="ability" data-use="${esc(i.id)}">Utiliser</button>`:''}</div>`).join('')||'<p class="meta">Aucun objet.</p>'}`).join('')}
function renderHistory(){let logs=state.history;
 $('#journalMechanical').hidden=journalPane!=='mechanical';$('#journalNotes').hidden=journalPane!=='notes';
 $$('[data-journal-tab]').forEach(b=>b.classList.toggle('active',b.dataset.journalTab===journalPane));
 $('#journalCount').textContent=logs.length+' événement'+(logs.length>1?'s':'');
 $('#journalBody').innerHTML=logs.length?logs.slice(0,100).map(e=>{let time=new Date(e.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),kind=esc(e.kind||'action');return '<article class="journal-entry journal-'+kind+'"><div class="journal-entry-top"><span>'+time+' · Round '+e.round+'</span><span class="journal-kind">'+kind+'</span></div><b>'+esc(e.title)+'</b><p>'+esc(e.detail)+'</p></article>'}).join(''):'<div class="journal-empty">Aucune action enregistrée.</div>';
 $('#npcBody').innerHTML=state.npcs.map((n,i)=>`<div class="npc-row">${n.image&&/^(https:\/\/|data:image\/)/.test(n.image)?`<img src="${esc(n.image)}" alt="">`:''}<div><b>${esc(n.name)}</b><p>${esc(n.note)}</p></div><button class="ability" data-npc="${i}">Modifier</button><button class="ability danger" data-npc-remove="${i}">×</button></div>`).join('')||'<div class="journal-empty">Aucun personnage rencontré enregistré.</div>';
 $('#preview').textContent=state.notes||'L’aperçu apparaîtra ici.';$('#notesPreview').open=state.preview;
}
async function itemEditor(id){let old=state.items.find(i=>i.id===id),data=await askText(old?'Modifier un objet':'Ajouter un objet',[{key:'name',label:'Nom',max:160},{key:'qty',label:'Quantité',type:'number'},{key:'note',label:'Description / notes',type:'textarea'},{key:'image',label:'Image HTTPS (ou choisir un fichier après enregistrement)'}],old||{qty:1});if(!data)return;let qty=Number(data.qty);if(!data.name.trim()||!Number.isInteger(qty)||qty<0||qty>9999){message('Nom ou quantité invalide.');return}let category=old?.category||'misc',equipped=old?.equipped||false;let c=await choose('Catégorie et port',`<label>Catégorie <select name="category"><option value="equipment" ${category==='equipment'?'selected':''}>Équipement</option><option value="misc" ${category==='misc'?'selected':''}>Divers / consommable</option></select></label><label>Équipé <select name="equipped"><option value="no">Non</option><option value="yes" ${equipped?'selected':''}>Oui</option></select></label>`,[{label:'Valider',value:'ok'},{label:'Annuler',value:null}]);if(!c.choice)return;let obj={id:old?.id||crypto.randomUUID(),name:data.name.trim().slice(0,160),qty,note:data.note.slice(0,5000),image:/^(https:\/\/|data:image\/)/.test(data.image)?data.image:old?.image||'',category:c.data.category,equipped:c.data.equipped==='yes'};transaction(old?'Objet modifié':'Objet ajouté',()=>{if(old)state.items[state.items.indexOf(old)]=obj;else state.items.push(obj);return `${obj.name} ×${obj.qty}.`});let p=await choose('Image de l’objet',`<p>Ajouter une icône locale ou supprimer l’objet ?</p>`,[{label:'Choisir une image',value:'image'},...(old?[{label:'Supprimer l’objet',value:'delete'}]:[]),{label:'Terminer',value:null}]);if(p.choice==='image'){$('#imageInput').dataset.item=obj.id;$('#imageInput').click()}if(p.choice==='delete'&&confirm('Supprimer cet objet ?'))transaction('Objet supprimé',()=>{state.items=state.items.filter(i=>i.id!==obj.id);return obj.name})}
function download(name,body,type='application/json'){let url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function npcEditor(index){let old=state.npcs[index]||{},data=await askText(old.name?'Modifier le PNJ':'Ajouter un PNJ',[{key:'name',label:'Nom',max:160},{key:'note',label:'Notes',type:'textarea'},{key:'image',label:'Image HTTPS'}],old);if(!data||!data.name.trim())return;let npc={name:data.name.trim().slice(0,160),note:data.note.slice(0,5000),image:/^https:\/\//.test(data.image)?data.image:''};transaction('Fiche PNJ',()=>{if(index>=0)state.npcs[index]=npc;else state.npcs.push(npc);return npc.name})}
window.__CompanionBridge={id:'samoth',name:'Samoth',maxHp:72,read:()=>state,ac:()=>15,inventory:()=>state.items,resources:s=>({slots:s.slots,sorceryPoints:s.sp,featPoints:s.featSp,wings:s.wings}),statuses:s=>[s.dragon?'dragon invoqué':null,s.flameArmed?'flamme armée':null].filter(Boolean),custom:s=>({phase:s.phase,dragon:s.dragon?{...s.dragon,eco:s.dragonEco,damage:s.dragonDamage}:null,metamagic:s.meta,sharedResistance:s.sharedResistance}),actors:()=>[{id:'samoth',name:'Samoth'},...(state.dragon?[{id:'dragon',name:'Esprit draconique',owner:'samoth'}]:[])],pending:()=>document.querySelector('#resolution.hit-confirm[open]')?{actor:state.phase,roll:document.querySelector('#resolutionBody .hit-roll')?.textContent}:null,lastHit:()=>window.__lastAttackHit??null,commands:{damage:n=>applyIncomingHp(n,'damage'),heal:n=>applyIncomingHp(n,'heal'),setHP:n=>transaction('PV fixés',()=>{state.hp=Math.min(72,n);return `${state.hp}/72 PV.`}),setTemporaryHP:n=>transaction('PV temporaires',()=>{state.tempHp=n;return `${n} PV temporaires.`}),setResource:(k,v)=>transaction('Ressource ajustée',()=>{if(k==='sp')state.sp=Math.min(10,v);else if(k==='featSp')state.featSp=Math.min(2,v);else if(/^slot[1-5]$/.test(k))state.slots[k.slice(4)]=Math.min(MAX[k.slice(4)],v);else throw Error('Ressource inconnue');return `${k} : ${v}`}),changeResource:(k,d)=>window.__CompanionBridge.commands.setResource(k,Math.max(0,(k.startsWith('slot')?state.slots[k.slice(4)]:state[k])+d)),setRollMode:m=>{if(!['normal','adv','dis'].includes(m))throw Error('Mode indisponible');state.rollMode=m;persist();render()},nextTurn,applyHitDecision:hit=>{if(!pendingHitDecision)throw Error('Aucune attaque en attente');pendingHitDecision(hit)},clearConcentration:stopConcentration,setConcentration:name=>transaction('Concentration',()=>{state.concentration=String(name||'');return state.concentration}),addInventoryItem:item=>transaction('Objet ajouté',()=>{let i={id:crypto.randomUUID(),name:String(item.name).slice(0,160),qty:Math.max(0,Number(item.qty)||1),category:item.category==='equipment'?'equipment':'misc',note:String(item.note||''),image:'',equipped:false};state.items.push(i);return i.name}),updateInventory:item=>transaction('Objet modifié',()=>{let i=state.items.find(x=>x.id===item.id);if(!i)throw Error('Objet inconnu');Object.assign(i,{qty:Math.max(0,Number(item.qty??i.qty)),note:String(item.note??i.note)});return i.name}),removeInventoryItem:id=>transaction('Objet retiré',()=>{state.items=state.items.filter(i=>i.id!==id);return String(id)}),undo:undoSamoth}};
$('#notes').value=state.notes;if(loadError)message(loadError);renderSocial();render();if(!loadError&&state.history.length){let last=state.history[0];$('#resultTitle').textContent=last.title;$('#resultText').textContent=last.detail}if(state.phase==='dragon')view('dragon');else{updateMobileNavigation('combat');updateDesktopNavigation('combat')}
$$('.nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-mobile-view]').forEach(b=>b.onclick=()=>view(b.dataset.mobileView));$('#mobileSubnav').onclick=e=>{let b=e.target.closest('[data-sub-view]');if(b)view(b.dataset.subView)};$$('[data-power-tab]').forEach(b=>b.onclick=()=>showPowerTab(b.dataset.powerTab));$('#spellList').onclick=e=>{let button=e.target.closest('[data-spell-filter]');if(!button)return;spellFilter=button.dataset.spellFilter;renderSpellList()};$('#nextTurn').onclick=nextTurn;$('#shortRest').onclick=()=>rest(false);$('#longRest').onclick=()=>rest(true);$('#resultClose').onclick=e=>{e.stopPropagation();clearTimeout(resultTimer);$('#result').classList.toggle('collapsed')};$('#result').onclick=e=>{if(!e.target.closest('button')&&$('#result').classList.contains('collapsed')){$('#result').classList.remove('collapsed');clearTimeout(resultTimer)}};$('#concButton').onclick=()=>{if(state.concentration)stopConcentration();else{showPowerTab('spells');view('powers')}};function undoSamoth(){if(!state.undo)return;let prev=clone(state.undo);prev.undo=null;state=prev;persist();render();message('Dernière opération annulée ; ressources et journal restaurés.')}$('#undo').onclick=undoSamoth;
$('#combatSpell').addEventListener('change',e=>{let spell=getSpell(e.target.value);if(!spell)return;state.selectedSpell=spell.id;if(STAFF_ONLY.has(spell.id)||!metaFits(spell,state.meta))state.meta='none';if(spell.kind!=='attack')$('#manual').value='';persist();render()});
function refreshCastResource(){let s=selectedSpell(),d=readCastDraft(s),staff=STAFF_SPELLS[s.id],level=$('#castLevel');if(level)level.disabled=!!d.useStaff;if(staff&&d.useStaff)$('#casterResource').textContent=`Bâton · ${state.staff}/8 charges · coût ${staff.cost}`;else if(s.lv)$('#casterResource').textContent=s.id==='cure'&&d.free?'usage gratuit disponible':`N${d.level} · ${state.slots[d.level]}/${MAX[d.level]} disponibles`;$('#combatCast').disabled=!!(staff&&d.useStaff&&(state.staff<staff.cost||state.eco.action||state.phase==='dragon'))}$('#castSetup').addEventListener('input',refreshCastResource);$('#castSetup').addEventListener('change',refreshCastResource);
$('#hp').onchange=e=>{let n=Number(e.target.value);if(!Number.isFinite(n)||n<0||n>72){render();return}transaction('PV ajustés',()=>{let old=state.hp;state.hp=n;return `${old} → ${n}/72.`})};$('#tempHp').onchange=e=>{let n=Number(e.target.value);if(!Number.isFinite(n)||n<0||n>999){render();return}transaction('PV temporaires ajustés',()=>{state.tempHp=n;return `${n} PV temporaires.`})};
$('#notes').oninput=e=>{state.notes=e.target.value;$('#preview').textContent=state.notes||'Aucune note.';persist()};$('#notesPreview').ontoggle=e=>{state.preview=e.target.open;persist()};$('#journalSearch').oninput=e=>{let q=e.target.value.trim().toLocaleLowerCase('fr');$('#journalBody .journal-entry').forEach(line=>line.hidden=!!q&&!line.textContent.toLocaleLowerCase('fr').includes(q));};
$('#addItem').onclick=()=>itemEditor();$('#addNpc').onclick=()=>npcEditor(-1);$('#export').onclick=()=>download('samoth-companion-v3.json',JSON.stringify({format:'samoth-companion-v3',schema:3,state:{...state,undo:null}},null,2));$('#import').onclick=()=>$('#fileInput').click();$('#reset').onclick=()=>{if(!confirm('Effacer la partie de Samoth, inventaire et notes compris ? Exportez-la d’abord si besoin.'))return;let previous=localStorage.getItem(KEY);try{localStorage.setItem(KEY+':backup',previous||'');state=fresh();persist();location.reload()}catch{message('Remise à zéro impossible.')}};
$('#fileInput').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>2500000)throw Error('Fichier trop volumineux.');let doc=JSON.parse(await file.text());if(doc.format!=='samoth-companion-v3'||doc.schema!==3||!doc.state||!Array.isArray(doc.state.items)||!Array.isArray(doc.state.history)||!doc.state.slots||!doc.state.eco||!Number.isFinite(doc.state.hp))throw Error('Sauvegarde Samoth V3 invalide.');if(!confirm('Remplacer la partie actuelle ? Une copie sera conservée localement.'))return;localStorage.setItem(KEY+':backup',localStorage.getItem(KEY)||'');state={...doc.state,undo:null};persist();location.reload()}catch(err){message(err.message)}finally{e.target.value=''}};
$('#imageInput').onchange=async e=>{let f=e.target.files[0],id=e.target.dataset.item;if(!f)return;if(!f.type.startsWith('image/')||f.size>160000){message('Image requise, 160 Ko maximum pour préserver le stockage local.');return}let url=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});transaction('Icône ajoutée',()=>{let item=state.items.find(i=>i.id===id);if(!item)return false;item.image=url;return item.name});e.target.value=''};
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.slotLevel){let level=b.dataset.slotLevel,index=Number(b.dataset.slotIndex),before=state.slots[level];transaction('Emplacement ajusté',()=>{state.slots[level]=index<before?index:index+1;return `Niveau ${level} : ${before} → ${state.slots[level]}/${MAX[level]} disponibles.`});return}if(b.dataset.staffSpell){await useStaffSpell(b.dataset.staffSpell);return}if(b.dataset.cast){if(b.id!=='combatCast'){state.selectedSpell=b.dataset.cast;if(!metaFits(selectedSpell(),state.meta))state.meta='none';persist();render();view('combat');$('#castSetup').scrollIntoView({block:'center',behavior:'smooth'});return}await cast(b.dataset.cast);return}if(b.dataset.dragon){await dragonAction(b.dataset.dragon);return}if(b.dataset.ability){await useAbility(b.dataset.ability);return}if(b.dataset.meta){state.meta=b.dataset.meta;persist();render();return}if(b.dataset.rollmode){state.rollMode=b.dataset.rollmode;persist();render();return}if(b.dataset.econ){let key=b.dataset.econ;if(state.phase==='dragon'&&key==='bonus')return;transaction('Économie du tour',()=>{let eco=state.phase==='dragon'?state.dragonEco:state.eco;eco[key]=!eco[key];return `${key} ${eco[key]?'utilisé':'restauré manuellement'}.`});return}if(b.dataset.hp){let n=await askNumber(b.dataset.hp==='damage'?'Dégâts subis':'Soins reçus',1,0,999);if(n===null)return;applyIncomingHp(n,b.dataset.hp);return}if(b.dataset.socialPane){socialPane=b.dataset.socialPane;renderSocial();return}if(b.dataset.socialMode){socialMode=b.dataset.socialMode;renderSocial();return}if(b.dataset.journalTab){journalPane=b.dataset.journalTab;renderHistory();return}if(b.dataset.roll){let a=roll(20),b2=socialMode==='normal'?null:roll(20),n=b2===null?a:socialMode==='adv'?Math.max(a,b2):Math.min(a,b2),bonus=Number(b.dataset.bonus),text=`d20 ${b2===null?a:a+' / '+b2+' → '+n} ${bonus>=0?'+':'−'}${Math.abs(bonus)} = ${n+bonus}${n===1?' · 1 naturel':n===20?' · 20 naturel':''}`;transaction(b.dataset.roll,()=>text);window.CompanionSocialDice?.show({label:b.dataset.roll,dice:b2===null?a:[a,b2],bonus,total:n+bonus,mode:socialMode});return}if(b.dataset.item){await itemEditor(b.dataset.item);return}if(b.dataset.use){let item=state.items.find(i=>i.id===b.dataset.use);if(item&&item.qty)transaction('Objet utilisé',()=>{if(item.category!=='equipment')item.qty--;return `${item.name} · ${item.qty} restant(s). ${item.category==='equipment'?'Équipement conservé.':'Consommable dépensé.'} Effet à appliquer selon l’objet.`});return}if(b.dataset.npc){await npcEditor(Number(b.dataset.npc));return}if(b.dataset.npcRemove&&confirm('Supprimer ce PNJ ?'))transaction('PNJ supprimé',()=>{let n=state.npcs.splice(Number(b.dataset.npcRemove),1)[0];return n?.name||''})});
