const MAXS={1:4,2:3,3:3,4:3,5:2};
const BASE={hp:72,spCore:10,spBonus:2,slots:{1:4,2:3,3:3,4:3,5:2},turn:1,turnDamage:0,eco:{action:false,bonus:false,reaction:false},concentration:'',metaArmed:'',metaCost:0,pureReady:false,pureUse:1,wings:4,vial:1,heal:1,staff:8,dragon:false,dragonHp:50,log:[]};
let S=Object.assign(structuredClone(BASE),JSON.parse(localStorage.getItem('samoth-premium-v1')||'null')||{});S.slots=Object.assign({},BASE.slots,S.slots||{});S.eco=Object.assign({},BASE.eco,S.eco||{});
const $=id=>document.getElementById(id),d=n=>Math.floor(Math.random()*n)+1;
function save(){localStorage.setItem('samoth-premium-v1',JSON.stringify(S))}
function particles(e,kind,count=22){let glyph=kind==='pure'?'✦':kind==='dragon'?'◇':'❄',color=kind==='pure'?'#ffd09a':kind==='dragon'?'#e4e8ef':'#ddfbff';for(let i=0;i<count;i++){let p=document.createElement('span'),a=Math.random()*Math.PI*2,dist=80+Math.random()*320;p.className='fx-particle';p.textContent=glyph;p.style.color=color;p.style.fontSize=(14+Math.random()*30)+'px';p.style.setProperty('--x',(Math.cos(a)*dist)+'px');p.style.setProperty('--y',(Math.sin(a)*dist)+'px');p.style.setProperty('--s',(.7+Math.random()*1.4));p.style.setProperty('--r',(Math.floor(Math.random()*520)-260)+'deg');p.style.animation='particleFly '+(.65+Math.random()*.55)+'s ease-out forwards';e.appendChild(p)}}
function fx(c,layer=1){let e=$(layer===1?'fx':'fx2');e.className='';e.innerHTML='';void e.offsetWidth;e.className=c;let kind=c.includes('pure')?'pure':c.includes('dragon')?'dragon':'ice';if(!c.includes('veil')&&!c.includes('haste')&&!c.includes('rayon'))particles(e,kind,c.includes('vortex')?32:c.includes('grele')?34:c.includes('cone')?30:c.includes('souffle')?36:22);setTimeout(()=>{e.className='';e.innerHTML=''},1550)}
function show(t,c){S.log.unshift(t);S.log=S.log.slice(0,30);$('rb').textContent=t;$('ribbon').classList.add('show');setTimeout(()=>$('ribbon').classList.remove('show'),2400);if(c)fx(c);render();save()}
function dice(n,s,cold=false){let a=[];for(let i=0;i<n;i++){let x=d(s);if(cold&&x===1)x=2;a.push(x)}return{a,total:a.reduce((x,y)=>x+y,0)}}
function useEco(k){if(S.eco[k]){show(k+' déjà utilisée ce tour.');return false}S.eco[k]=true;return true}
function spendSlot(l){if(!l)return true;if(S.slots[l]<1){show('Aucun emplacement N'+l+'.');return false}S.slots[l]--;return true}
function spendMeta(level){if(!S.metaArmed)return'';let cost=S.metaArmed==='Jumelé'?Math.max(1,level):S.metaCost,total=S.spCore+S.spBonus;if(total<cost){show('Pas assez de points de métamagie.');return false}let b=Math.min(S.spBonus,cost);S.spBonus-=b;S.spCore-=cost-b;let n=S.metaArmed;S.metaArmed='';S.metaCost=0;return n}
function armMeta(n,c){if(S.metaArmed===n){S.metaArmed='';S.metaCost=0}else{S.metaArmed=n;S.metaCost=c}render();save()}
function clearMeta(){S.metaArmed='';S.metaCost=0;render();save()}
function pureBonus(level){if(!S.pureReady||level<1)return{total:0,text:''};let r=dice(level,10);S.pureReady=false;S.pureUse=0;fx('fx-pure',2);return{total:r.total,text:' + Flammes pures '+r.total+' radiant ('+r.a.join('+')+')'}}
function addDamage(x){S.turnDamage+=x}function chgHp(v){S.hp=Math.max(0,Math.min(72,S.hp+v));render();save()}function setHp(){S.hp=Math.max(0,Math.min(72,Number($('hpInput').value)||0));render();save()}
function coldFxFor(name){if(name==='Rayon de givre')return'fx-rayon-givre';if(name==='Gelure')return'fx-gelure';if(name==='Vortex de glace')return'fx-vortex-glace';if(name==='Cône de froid')return'fx-cone-froid';if(name.includes('Orbe chromatique'))return'fx-orbe-froid';return'fx-cold'}
function attackSpell(name,level,nd,sd,cold){if(!useEco('action'))return;if(level&&!spendSlot(level)){S.eco.action=false;return}let meta=spendMeta(level);if(meta===false){S.eco.action=false;if(level)S.slots[level]++;return}let nat=d(20),r=dice(nd,sd,cold),dmg=r.total+(cold?3:0),p=pureBonus(level);dmg+=p.total;addDamage(dmg);if(nat===20)fx('crit',2);show(name+' : '+nat+' +10 = '+(nat+10)+'\nDégâts '+dmg+(cold?' froid':'')+(p.text?'\n'+p.text:'')+(meta?'\nMétamagie : '+meta:''),cold?coldFxFor(name):'')}
function saveSpell(name,level,saveName,nd,sd,cold){if(!useEco('action'))return;if(level&&!spendSlot(level)){S.eco.action=false;return}let meta=spendMeta(level);if(meta===false){S.eco.action=false;if(level)S.slots[level]++;return}let r=dice(nd,sd,cold),dmg=r.total+(cold?3:0),p=pureBonus(level);dmg+=p.total;addDamage(dmg);show(name+' · '+saveName+' DD18\nÉchec : '+dmg+' dégâts · réussite : moitié'+(p.text?'\n'+p.text:'')+(meta?'\nMétamagie : '+meta:''),cold?coldFxFor(name):'')}
function iceStorm(){if(!useEco('action'))return;if(!spendSlot(4)){S.eco.action=false;return}let meta=spendMeta(4);if(meta===false){S.eco.action=false;S.slots[4]++;return}let a=dice(2,8),b=dice(4,6,true),p=pureBonus(4),dmg=a.total+b.total+3+p.total;addDamage(dmg);show('Tempête de grêle · DEX DD18\n'+a.total+' contondant + '+(b.total+3)+' froid = '+dmg+(p.text?'\n'+p.text:'')+(meta?'\nMétamagie : '+meta:''),'fx-tempete-grele')}
function castUtility(name,level,conc,eco='action',effect){if(!useEco(eco))return;if(!spendSlot(level)){S.eco[eco]=false;return}let meta=spendMeta(level);if(meta===false){S.eco[eco]=false;S.slots[level]++;return}let p=pureBonus(level);if(p.total)addDamage(p.total);if(conc){if(S.concentration.includes('draconique'))S.dragon=false;S.concentration=name}show(name+' lancé N'+level+(conc?' · concentration':'')+(meta?'\nMétamagie : '+meta:'')+(p.text?'\n'+p.text:''),effect)}
function reactionSpell(name,level,effect){if(!useEco('reaction'))return;if(!spendSlot(level)){S.eco.reaction=false;return}show(name+' N'+level+' activé en réaction.',effect)}
function armPure(){if(!S.pureUse)return show('Flammes de la magie pure déjà utilisées aujourd’hui.');S.pureReady=!S.pureReady;show(S.pureReady?'Flammes pures armées : le prochain sort de niveau 1+ sera renforcé.':'Flammes pures désarmées.',S.pureReady?'fx-pure':null)}
function createSlot(l,c){if(S.spCore<c)return show('Pas assez de points convertibles.');if(S.slots[l]>=MAXS[l])return show('Emplacements N'+l+' déjà au maximum.');S.spCore-=c;S.slots[l]++;show('Création d’un emplacement N'+l+'.')}
function takeDamage(){let x=Math.max(0,Number($('incoming').value)||0);if(!x)return;S.hp=Math.max(0,S.hp-x);let line='Samoth reçoit '+x+' dégâts → '+S.hp+' PV.';if(S.concentration){let dc=Math.max(10,Math.floor(x/2)),roll=d(20)+6,ok=roll>=dc;line+='\nConcentration : '+roll+' vs DD '+dc+' '+(ok?'✓':'✗');if(!ok){line+=' · '+S.concentration+' prend fin.';S.concentration='';S.dragon=false}}show(line)}
function endConc(){if(!S.concentration)return;let old=S.concentration;S.concentration='';if(old.includes('draconique'))S.dragon=false;show('Concentration terminée : '+old+'.')}
function useWings(){if(!S.wings)return show('Ailes protectrices épuisées.');if(!useEco('reaction'))return;S.wings--;show('Ailes protectrices : +4 CA contre cette attaque.','fx-shield')}
function summonDragon(){if(!useEco('action'))return;if(!spendSlot(5)){S.eco.action=false;return}let meta=spendMeta(5);if(meta===false){S.eco.action=false;S.slots[5]++;return}S.dragon=true;S.dragonHp=50;S.concentration='Convocation d’esprit draconique';show('Esprit draconique d’argent invoqué.'+(meta?'\nMétamagie : '+meta:''),'fx-dragon')}
function dragonRend(){if(!S.dragon)return show('Aucun esprit draconique actif.');let a=d(20)+10,b=d(20)+10,r1=d(6)+9,r2=d(6)+9;addDamage(r1+r2);show('Déchirement ×2\nAttaques '+a+' / '+b+'\nDégâts '+r1+' / '+r2,'fx-dragon')}
function dragonBreath(){if(!S.dragon)return show('Aucun esprit draconique actif.');let r=dice(2,6);addDamage(r.total);show('Souffle froid · DEX DD18\n'+r.total+' dégâts · réussite : moitié','fx-souffle-dragon')}
function staff(v){S.staff=Math.max(0,Math.min(8,S.staff+v));render();save()}function staffRecharge(){let x=d(4)+2;S.staff=Math.min(8,S.staff+x);show('Bâton : +'+x+' charges → '+S.staff+'/8.')}
function useVial(){if(!S.vial)return show('Fiole déjà utilisée.');if(S.spCore>=10)return show('Points convertibles déjà au maximum.');S.vial=0;S.spCore=Math.min(10,S.spCore+5);show('Fiole sanguine : +5 points convertibles.')}
function freeHeal(){if(!S.heal)return show('Soins gratuit déjà utilisé.');S.heal=0;let x=d(8)+3;S.hp=Math.min(72,S.hp+x);show('Soins : +'+x+' PV.','fx-heal')}function woodHeal(){let x=d(6);S.hp=Math.min(72,S.hp+x);show('Anneau en bois : +'+x+' PV.','fx-heal')}
function nextTurn(){S.turn++;S.turnDamage=0;S.eco={action:false,bonus:false,reaction:false};show('Tour '+S.turn+' — économie d’action et dégâts du tour réinitialisés.')}
function shortRest(){S.eco={action:false,bonus:false,reaction:false};show('Repos court : économie d’action réinitialisée.')}
function longRest(){Object.assign(S,structuredClone(BASE));show('Repos long : toutes les ressources sont restaurées.')}
function clearLog(){S.log=[];render();save()}function resetAll(){if(confirm('Réinitialiser Samoth ?')){localStorage.removeItem('samoth-premium-v1');location.reload()}}
function renderSlots(){let h='';for(let l=1;l<=5;l++){h+='<div class="slotrow"><b>N'+l+'</b><div class="pips">';for(let i=0;i<MAXS[l];i++)h+='<button class="pip '+(i<S.slots[l]?'':'off')+'" onclick="S.slots['+l+']='+(i<S.slots[l]?i:i+1)+';render();save()"></button>';h+='</div><div class="slotcount">'+S.slots[l]+'/'+MAXS[l]+'</div></div>'}$('slots').innerHTML=h}
function render(){$('hpInput').value=S.hp;$('metaTotal').textContent=(S.spCore+S.spBonus)+' / 12';$('metaSplit').textContent=S.spCore+' convertibles + '+S.spBonus+' méta-only';$('turnN').textContent=S.turn;$('turnDamage').textContent=S.turnDamage;$('concName').textContent=S.concentration||'Aucune';$('wingsText').textContent=S.wings;$('vialText').textContent=S.vial;$('healText').textContent=S.heal;$('staffText').textContent=S.staff+'/8';$('dragonHp').textContent=S.dragonHp+'/50';$('pureMiniBtn').classList.toggle('armed',S.pureReady);$('pureMiniState').textContent=S.pureReady?'Armé':'Prêt';for(let k of ['Action','Bonus','Reaction']){let key=k.toLowerCase(),e=$('eco'+k);e.classList.toggle('used',S.eco[key]);e.querySelector('span').textContent=S.eco[key]?'Utilisée':'Disponible'}document.querySelectorAll('.metachip[data-meta]').forEach(x=>x.classList.toggle('active',x.dataset.meta===S.metaArmed));$('log').textContent=S.log.length?S.log.join('\n\n'):'Prêt.';renderSlots();save()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.panel).classList.add('active')});render();